/* MyVitality i18n generator — single source of truth for site translations.
 * Key = original English string (as it appears in the page, whitespace-collapsed).
 * Value may include inline markup (links/strong/span) with single-quoted attrs.
 * Writes i18n/<lang>.json for every language. English needs no file (the HTML
 * is already English). Run: npm run i18n  (or: node i18n-build.js)
 */
const fs = require('fs');
const path = require('path');
const LANGS = ['tr', 'de', 'es', 'fr', 'it', 'ja', 'ko', 'pt', 'ru', 'zh', 'ar'];

const T = {
  // ── Navigation ──
  "Features": { tr:"Özellikler", de:"Funktionen", es:"Funciones", fr:"Fonctions", it:"Funzioni", ja:"機能", ko:"기능", pt:"Recursos", ru:"Возможности", zh:"功能", ar:"الميزات" },
  "Workout": { tr:"Antrenman", de:"Training", es:"Entreno", fr:"Séance", it:"Allenamento", ja:"ワークアウト", ko:"운동", pt:"Treino", ru:"Тренировка", zh:"训练", ar:"التمرين" },
  "Recovery": { tr:"Toparlanma", de:"Erholung", es:"Recuperación", fr:"Récupération", it:"Recupero", ja:"回復", ko:"회복", pt:"Recuperação", ru:"Восстановление", zh:"恢复", ar:"التعافي" },
  "Community": { tr:"Topluluk", de:"Community", es:"Comunidad", fr:"Communauté", it:"Comunità", ja:"コミュニティ", ko:"커뮤니티", pt:"Comunidade", ru:"Сообщество", zh:"社区", ar:"المجتمع" },
  "Pricing": { tr:"Fiyatlandırma", de:"Preise", es:"Precios", fr:"Tarifs", it:"Prezzi", ja:"料金", ko:"요금제", pt:"Preços", ru:"Цены", zh:"价格", ar:"الأسعار" },
  "Blog": { tr:"Blog", de:"Blog", es:"Blog", fr:"Blog", it:"Blog", ja:"ブログ", ko:"블로그", pt:"Blog", ru:"Блог", zh:"博客", ar:"المدونة" },
  "Get the app": { tr:"Uygulamayı al", de:"App holen", es:"Descargar app", fr:"Obtenir l'app", it:"Scarica l'app", ja:"アプリを入手", ko:"앱 받기", pt:"Obter o app", ru:"Установить", zh:"获取应用", ar:"احصل على التطبيق" },

  // ── Footer ──
  "Fitness, recovery and community in one app. Track workouts, understand your body and stay consistent — built for everyday athletes.": {
    tr:"Fitness, toparlanma ve topluluk tek uygulamada. Antrenmanlarını takip et, vücudunu anla ve istikrarlı kal — her gün spor yapanlar için tasarlandı.",
    de:"Fitness, Erholung und Community in einer App. Verfolge Workouts, verstehe deinen Körper und bleib dran — gebaut für Alltagssportler.",
    es:"Fitness, recuperación y comunidad en una sola app. Registra entrenamientos, entiende tu cuerpo y mantén la constancia — hecha para atletas de cada día.",
    fr:"Fitness, récupération et communauté dans une seule app. Suivez vos séances, comprenez votre corps et restez régulier — conçue pour les sportifs du quotidien.",
    it:"Fitness, recupero e comunità in un'unica app. Monitora gli allenamenti, capisci il tuo corpo e resta costante — pensata per gli atleti di ogni giorno.",
    ja:"フィットネス、回復、コミュニティを1つのアプリに。ワークアウトを記録し、体を理解し、継続しよう — 日々のアスリートのために。",
    ko:"피트니스, 회복, 커뮤니티를 하나의 앱에. 운동을 기록하고 몸을 이해하며 꾸준함을 유지하세요 — 일상 운동인을 위해 만들었습니다.",
    pt:"Fitness, recuperação e comunidade num só app. Acompanhe treinos, entenda seu corpo e mantenha a constância — feito para atletas do dia a dia.",
    ru:"Фитнес, восстановление и сообщество в одном приложении. Отслеживайте тренировки, понимайте своё тело и будьте последовательны — для тех, кто тренируется каждый день.",
    zh:"健身、恢复与社区，集于一个应用。记录训练，了解身体，保持坚持 — 为每一位日常运动者打造。",
    ar:"اللياقة والتعافي والمجتمع في تطبيق واحد. تابع تمارينك، افهم جسدك، وحافظ على الاستمرارية — مصمّم لرياضيي كل يوم."
  },
  "Product": { tr:"Ürün", de:"Produkt", es:"Producto", fr:"Produit", it:"Prodotto", ja:"製品", ko:"제품", pt:"Produto", ru:"Продукт", zh:"产品", ar:"المنتج" },
  "Company": { tr:"Şirket", de:"Unternehmen", es:"Empresa", fr:"Entreprise", it:"Azienda", ja:"会社", ko:"회사", pt:"Empresa", ru:"Компания", zh:"公司", ar:"الشركة" },
  "Legal": { tr:"Yasal", de:"Rechtliches", es:"Legal", fr:"Mentions légales", it:"Note legali", ja:"法的事項", ko:"법적 고지", pt:"Jurídico", ru:"Правовая информация", zh:"法律", ar:"قانوني" },
  "Workout tracker": { tr:"Antrenman takibi", de:"Workout-Tracker", es:"Registro de entrenos", fr:"Suivi des séances", it:"Tracker allenamenti", ja:"ワークアウト記録", ko:"운동 추적", pt:"Registro de treinos", ru:"Трекер тренировок", zh:"训练记录", ar:"متتبّع التمارين" },
  "Recovery tracker": { tr:"Toparlanma takibi", de:"Erholungs-Tracker", es:"Registro de recuperación", fr:"Suivi de récupération", it:"Tracker recupero", ja:"回復トラッカー", ko:"회복 추적", pt:"Registro de recuperação", ru:"Трекер восстановления", zh:"恢复记录", ar:"متتبّع التعافي" },
  "Sleep tracker": { tr:"Uyku takibi", de:"Schlaf-Tracker", es:"Registro de sueño", fr:"Suivi du sommeil", it:"Tracker del sonno", ja:"睡眠トラッカー", ko:"수면 추적", pt:"Registro de sono", ru:"Трекер сна", zh:"睡眠记录", ar:"متتبّع النوم" },
  "About": { tr:"Hakkında", de:"Über uns", es:"Acerca de", fr:"À propos", it:"Chi siamo", ja:"概要", ko:"소개", pt:"Sobre", ru:"О нас", zh:"关于", ar:"حول" },
  "Contact": { tr:"İletişim", de:"Kontakt", es:"Contacto", fr:"Contact", it:"Contatti", ja:"お問い合わせ", ko:"문의", pt:"Contato", ru:"Контакты", zh:"联系", ar:"اتصل بنا" },
  "Privacy Policy": { tr:"Gizlilik Politikası", de:"Datenschutz", es:"Política de privacidad", fr:"Confidentialité", it:"Privacy", ja:"プライバシーポリシー", ko:"개인정보 처리방침", pt:"Política de privacidade", ru:"Политика конфиденциальности", zh:"隐私政策", ar:"سياسة الخصوصية" },
  "Terms": { tr:"Koşullar", de:"AGB", es:"Términos", fr:"Conditions", it:"Termini", ja:"利用規約", ko:"이용약관", pt:"Termos", ru:"Условия", zh:"条款", ar:"الشروط" },
  "© 2026 MyVitality. All rights reserved.": { tr:"© 2026 MyVitality. Tüm hakları saklıdır.", de:"© 2026 MyVitality. Alle Rechte vorbehalten.", es:"© 2026 MyVitality. Todos los derechos reservados.", fr:"© 2026 MyVitality. Tous droits réservés.", it:"© 2026 MyVitality. Tutti i diritti riservati.", ja:"© 2026 MyVitality. 全著作権所有。", ko:"© 2026 MyVitality. All rights reserved.", pt:"© 2026 MyVitality. Todos os direitos reservados.", ru:"© 2026 MyVitality. Все права защищены.", zh:"© 2026 MyVitality. 保留所有权利。", ar:"© 2026 MyVitality. جميع الحقوق محفوظة." },

  // ── Hero ──
  "MyVitality · Coming to iOS": { tr:"MyVitality · iOS'ta yakında", de:"MyVitality · Bald für iOS", es:"MyVitality · Pronto en iOS", fr:"MyVitality · Bientôt sur iOS", it:"MyVitality · Presto su iOS", ja:"MyVitality · iOSに近日登場", ko:"MyVitality · iOS 출시 예정", pt:"MyVitality · Em breve no iOS", ru:"MyVitality · Скоро в iOS", zh:"MyVitality · 即将登陆 iOS", ar:"MyVitality · قريبًا على iOS" },
  "Train with clarity.": {
    tr:"Netlikle <span class='grad'>antrenman yap.</span>",
    de:"Trainiere mit <span class='grad'>Klarheit.</span>",
    es:"Entrena con <span class='grad'>claridad.</span>",
    fr:"Entraîne-toi avec <span class='grad'>clarté.</span>",
    it:"Allenati con <span class='grad'>chiarezza.</span>",
    ja:"<span class='grad'>明晰に</span>トレーニング。",
    ko:"<span class='grad'>명확하게</span> 트레이닝하세요.",
    pt:"Treine com <span class='grad'>clareza.</span>",
    ru:"Тренируйся с <span class='grad'>ясностью.</span>",
    zh:"训练，<span class='grad'>清晰可见。</span>",
    ar:"تدرّب بكل <span class='grad'>وضوح.</span>"
  },
  "GPS workouts, Apple Watch recovery, sleep and AI nutrition in one app — with a coach that reads your real data and tells you when to push and when to rest.": {
    tr:"GPS antrenmanları, Apple Watch toparlanması, uyku ve yapay zekâ beslenmesi tek uygulamada — gerçek verilerini okuyan ve ne zaman zorlanıp ne zaman dinleneceğini söyleyen bir koçla.",
    de:"GPS-Workouts, Apple-Watch-Erholung, Schlaf und KI-Ernährung in einer App — mit einem Coach, der deine echten Daten liest und dir sagt, wann du Gas geben und wann du ruhen solltest.",
    es:"Entrenamientos con GPS, recuperación con Apple Watch, sueño y nutrición con IA en una sola app — con un coach que lee tus datos reales y te dice cuándo exigirte y cuándo descansar.",
    fr:"Séances GPS, récupération Apple Watch, sommeil et nutrition par IA dans une seule app — avec un coach qui lit vos vraies données et vous dit quand pousser et quand récupérer.",
    it:"Allenamenti GPS, recupero con Apple Watch, sonno e nutrizione con IA in un'unica app — con un coach che legge i tuoi dati reali e ti dice quando spingere e quando riposare.",
    ja:"GPSワークアウト、Apple Watchの回復、睡眠、AI栄養管理を1つのアプリに — あなたの実データを読み、攻める時と休む時を教えるコーチ付き。",
    ko:"GPS 운동, Apple Watch 회복, 수면, AI 영양을 하나의 앱에 — 실제 데이터를 읽고 언제 밀어붙이고 언제 쉴지 알려주는 코치와 함께.",
    pt:"Treinos com GPS, recuperação com Apple Watch, sono e nutrição com IA num só app — com um coach que lê seus dados reais e diz quando avançar e quando descansar.",
    ru:"GPS-тренировки, восстановление с Apple Watch, сон и ИИ-питание в одном приложении — с тренером, который читает ваши реальные данные и подсказывает, когда ускориться, а когда отдохнуть.",
    zh:"GPS 训练、Apple Watch 恢复、睡眠和 AI 营养，集于一个应用 — 还有一位读懂你真实数据的教练，告诉你何时发力、何时休息。",
    ar:"تمارين GPS، وتعافي Apple Watch، والنوم، والتغذية بالذكاء الاصطناعي في تطبيق واحد — مع مدرّب يقرأ بياناتك الحقيقية ويخبرك متى تجتهد ومتى ترتاح."
  },
  "Get early access →": { tr:"Erken erişim al →", de:"Frühen Zugang sichern →", es:"Consigue acceso anticipado →", fr:"Accès anticipé →", it:"Accesso anticipato →", ja:"先行アクセスを取得 →", ko:"얼리 액세스 받기 →", pt:"Garantir acesso antecipado →", ru:"Получить ранний доступ →", zh:"获取抢先体验 →", ar:"احصل على وصول مبكر →" },
  "Free trial on iOS at launch · One email when it's live, no spam. See all features →": {
    tr:"Lansmanda iOS'ta ücretsiz deneme · Yayına girince tek e-posta, spam yok. <a href='/features/'>Tüm özellikleri gör →</a>",
    de:"Kostenlose Testphase auf iOS zum Start · Eine E-Mail, wenn es live ist, kein Spam. <a href='/features/'>Alle Funktionen ansehen →</a>",
    es:"Prueba gratuita en iOS en el lanzamiento · Un correo cuando esté disponible, sin spam. <a href='/features/'>Ver todas las funciones →</a>",
    fr:"Essai gratuit sur iOS au lancement · Un e-mail dès la mise en ligne, sans spam. <a href='/features/'>Voir toutes les fonctions →</a>",
    it:"Prova gratuita su iOS al lancio · Una mail quando è online, niente spam. <a href='/features/'>Vedi tutte le funzioni →</a>",
    ja:"公開時にiOSで無料トライアル · 公開されたらメール1通のみ、スパムなし。 <a href='/features/'>すべての機能を見る →</a>",
    ko:"출시 시 iOS에서 무료 체험 · 출시되면 이메일 한 통, 스팸 없음. <a href='/features/'>모든 기능 보기 →</a>",
    pt:"Teste grátis no iOS no lançamento · Um e-mail quando estiver no ar, sem spam. <a href='/features/'>Ver todos os recursos →</a>",
    ru:"Бесплатный период в iOS на старте · Одно письмо, когда выйдет, без спама. <a href='/features/'>Все возможности →</a>",
    zh:"上线时 iOS 免费试用 · 上线后仅发一封邮件，无垃圾信息。 <a href='/features/'>查看全部功能 →</a>",
    ar:"تجربة مجانية على iOS عند الإطلاق · بريد واحد عند توفّره، بلا إزعاج. <a href='/features/'>عرض كل الميزات →</a>"
  },
  "Health metrics": { tr:"Sağlık metriği", de:"Gesundheitswerte", es:"Métricas de salud", fr:"Indicateurs santé", it:"Parametri di salute", ja:"健康指標", ko:"건강 지표", pt:"Métricas de saúde", ru:"Показатели здоровья", zh:"健康指标", ar:"مؤشرات صحية" },
  "Coach & nutrition": { tr:"Koç ve beslenme", de:"Coach & Ernährung", es:"Coach y nutrición", fr:"Coach & nutrition", it:"Coach e nutrizione", ja:"コーチと栄養", ko:"코치 & 영양", pt:"Coach e nutrição", ru:"Тренер и питание", zh:"教练与营养", ar:"مدرّب وتغذية" },
  "Data sold": { tr:"Satılan veri", de:"Verkaufte Daten", es:"Datos vendidos", fr:"Données vendues", it:"Dati venduti", ja:"販売データ", ko:"판매 데이터", pt:"Dados vendidos", ru:"Проданных данных", zh:"出售数据", ar:"بيانات تُباع" },
  "READY": { tr:"HAZIR", de:"BEREIT", es:"LISTO", fr:"PRÊT", it:"PRONTO", ja:"準備OK", ko:"준비됨", pt:"PRONTO", ru:"ГОТОВ", zh:"就绪", ar:"جاهز" },
  "RECOVERY SCORE": { tr:"TOPARLANMA SKORU", de:"ERHOLUNGS-SCORE", es:"PUNTUACIÓN DE RECUPERACIÓN", fr:"SCORE DE RÉCUPÉRATION", it:"PUNTEGGIO DI RECUPERO", ja:"回復スコア", ko:"회복 점수", pt:"PONTUAÇÃO DE RECUPERAÇÃO", ru:"ОЦЕНКА ВОССТАНОВЛЕНИЯ", zh:"恢复评分", ar:"درجة التعافي" },

  // ── Device strip ──
  "Works with any device that syncs to Apple Health": { tr:"Apple Health ile senkronize olan her cihazla çalışır", de:"Funktioniert mit jedem Gerät, das mit Apple Health synchronisiert", es:"Funciona con cualquier dispositivo que sincronice con Apple Health", fr:"Compatible avec tout appareil synchronisé à Apple Health", it:"Funziona con qualsiasi dispositivo che si sincronizza con Apple Health", ja:"Apple Healthと同期するあらゆるデバイスに対応", ko:"Apple Health와 동기화되는 모든 기기와 호환", pt:"Funciona com qualquer dispositivo que sincroniza com o Apple Health", ru:"Работает с любым устройством, синхронизирующимся с Apple Health", zh:"兼容任何同步到 Apple Health 的设备", ar:"يعمل مع أي جهاز يتزامن مع Apple Health" },
  "MyVitality reads from Apple Health — if your device syncs to Apple Health, it works automatically.": { tr:"MyVitality, Apple Health'ten okur — cihazın Apple Health ile senkronize oluyorsa otomatik çalışır.", de:"MyVitality liest aus Apple Health — wenn dein Gerät mit Apple Health synchronisiert, funktioniert es automatisch.", es:"MyVitality lee de Apple Health — si tu dispositivo sincroniza con Apple Health, funciona automáticamente.", fr:"MyVitality lit depuis Apple Health — si votre appareil se synchronise à Apple Health, tout fonctionne automatiquement.", it:"MyVitality legge da Apple Health — se il tuo dispositivo si sincronizza con Apple Health, funziona automaticamente.", ja:"MyVitalityはApple Healthから読み取ります — お使いのデバイスがApple Healthと同期していれば自動で機能します。", ko:"MyVitality는 Apple Health에서 데이터를 읽습니다 — 기기가 Apple Health와 동기화되면 자동으로 작동합니다.", pt:"O MyVitality lê do Apple Health — se o seu dispositivo sincroniza com o Apple Health, funciona automaticamente.", ru:"MyVitality читает данные из Apple Health — если ваше устройство синхронизируется с Apple Health, всё работает автоматически.", zh:"MyVitality 从 Apple Health 读取数据 — 只要你的设备同步到 Apple Health，即可自动工作。", ar:"يقرأ MyVitality من Apple Health — إذا كان جهازك يتزامن مع Apple Health، فسيعمل تلقائيًا." },

  // ── 01 Problem ──
  "01 — The problem": { tr:"01 — Sorun", de:"01 — Das Problem", es:"01 — El problema", fr:"01 — Le problème", it:"01 — Il problema", ja:"01 — 課題", ko:"01 — 문제", pt:"01 — O problema", ru:"01 — Проблема", zh:"01 — 问题", ar:"01 — المشكلة" },
  "Tracking your fitness shouldn't be this hard": { tr:"Fitness'ını takip etmek bu kadar zor olmamalı", de:"Fitness-Tracking sollte nicht so schwer sein", es:"Seguir tu forma física no debería ser tan difícil", fr:"Suivre sa forme ne devrait pas être si difficile", it:"Monitorare la tua forma non dovrebbe essere così difficile", ja:"フィットネスの記録はこんなに難しくていいはずがない", ko:"피트니스 기록이 이렇게 어려울 필요는 없습니다", pt:"Acompanhar sua forma física não deveria ser tão difícil", ru:"Следить за формой не должно быть так сложно", zh:"记录健身本不该这么难", ar:"تتبّع لياقتك لا ينبغي أن يكون بهذه الصعوبة" },
  "Most people quit tracking because the tools get in the way. Notes get messy, spreadsheets get abandoned, and five separate apps never talk to each other.": { tr:"Çoğu insan, araçlar engel olduğu için takibi bırakır. Notlar karışır, tablolar terk edilir ve beş ayrı uygulama birbiriyle hiç konuşmaz.", de:"Die meisten hören mit dem Tracking auf, weil die Tools im Weg stehen. Notizen werden chaotisch, Tabellen aufgegeben, und fünf einzelne Apps reden nie miteinander.", es:"La mayoría deja de registrar porque las herramientas estorban. Las notas se desordenan, las hojas de cálculo se abandonan y cinco apps distintas nunca se comunican.", fr:"La plupart abandonnent le suivi parce que les outils gênent. Les notes deviennent brouillonnes, les tableurs sont abandonnés, et cinq apps distinctes ne communiquent jamais.", it:"La maggior parte smette di monitorare perché gli strumenti intralciano. Le note diventano caotiche, i fogli di calcolo vengono abbandonati e cinque app separate non si parlano mai.", ja:"多くの人はツールが邪魔で記録をやめてしまう。メモは散らかり、表計算は放置され、5つの別々のアプリは決して連携しない。", ko:"대부분은 도구가 방해가 되어 기록을 그만둡니다. 메모는 엉키고, 스프레드시트는 방치되며, 다섯 개의 앱은 서로 연동되지 않습니다.", pt:"A maioria desiste de registrar porque as ferramentas atrapalham. As notas viram bagunça, as planilhas são abandonadas e cinco apps separados nunca conversam entre si.", ru:"Большинство бросает вести учёт, потому что инструменты мешают. Заметки путаются, таблицы забрасываются, а пять отдельных приложений не общаются друг с другом.", zh:"大多数人放弃记录，是因为工具碍事。笔记凌乱，表格被弃用，五个独立的应用彼此从不互通。", ar:"يتوقف معظم الناس عن التتبّع لأن الأدوات تعيقهم. تتشتّت الملاحظات، وتُهمل الجداول، وخمسة تطبيقات منفصلة لا تتحدث مع بعضها أبدًا." },
  "Scattered data": { tr:"Dağınık veri", de:"Verstreute Daten", es:"Datos dispersos", fr:"Données éparpillées", it:"Dati sparsi", ja:"散らばったデータ", ko:"흩어진 데이터", pt:"Dados espalhados", ru:"Разрозненные данные", zh:"数据分散", ar:"بيانات مبعثرة" },
  "Runs in one app, sleep in another, food in a third. You never see how training, recovery and nutrition actually connect.": { tr:"Koşular bir uygulamada, uyku başka birinde, yemek üçüncüsünde. Antrenman, toparlanma ve beslenmenin gerçekte nasıl bağlandığını hiç göremezsin.", de:"Läufe in einer App, Schlaf in einer anderen, Essen in einer dritten. Du siehst nie, wie Training, Erholung und Ernährung wirklich zusammenhängen.", es:"Las carreras en una app, el sueño en otra, la comida en una tercera. Nunca ves cómo se conectan en realidad entreno, recuperación y nutrición.", fr:"Les courses dans une app, le sommeil dans une autre, l'alimentation dans une troisième. Vous ne voyez jamais comment entraînement, récupération et nutrition se relient vraiment.", it:"Le corse in un'app, il sonno in un'altra, il cibo in una terza. Non vedi mai come allenamento, recupero e nutrizione si collegano davvero.", ja:"ランニングは1つのアプリ、睡眠は別、食事はまた別。トレーニング・回復・栄養が実際どうつながっているかが見えない。", ko:"달리기는 한 앱, 수면은 다른 앱, 식사는 또 다른 앱. 훈련·회복·영양이 실제로 어떻게 연결되는지 결코 보이지 않습니다.", pt:"Corridas em um app, sono em outro, comida em um terceiro. Você nunca vê como treino, recuperação e nutrição realmente se conectam.", ru:"Пробежки в одном приложении, сон в другом, питание в третьем. Вы никогда не видите, как на самом деле связаны тренировки, восстановление и питание.", zh:"跑步在一个应用，睡眠在另一个，饮食在第三个。你永远看不到训练、恢复与营养之间真正的联系。", ar:"الجري في تطبيق، والنوم في آخر، والطعام في ثالث. لا ترى أبدًا كيف يرتبط التمرين والتعافي والتغذية فعليًا." },
  "No idea when to rest": { tr:"Ne zaman dinleneceğini bilememek", de:"Kein Gespür, wann ruhen", es:"Sin saber cuándo descansar", fr:"Aucune idée de quand récupérer", it:"Non sai quando riposare", ja:"いつ休むべきか分からない", ko:"언제 쉬어야 할지 모름", pt:"Sem saber quando descansar", ru:"Непонятно, когда отдыхать", zh:"不知何时该休息", ar:"لا تعرف متى ترتاح" },
  "You push hard every day and wonder why you're tired or injured. Without recovery and HRV data, you're guessing.": { tr:"Her gün sıkı çalışıyorsun ve neden yorgun ya da sakat olduğunu merak ediyorsun. Toparlanma ve HRV verisi olmadan tahmin yürütüyorsun.", de:"Du gibst jeden Tag Vollgas und fragst dich, warum du müde oder verletzt bist. Ohne Erholungs- und HRV-Daten rätst du nur.", es:"Te exiges al máximo cada día y te preguntas por qué estás cansado o lesionado. Sin datos de recuperación y HRV, vas a ciegas.", fr:"Vous forcez chaque jour et vous demandez pourquoi vous êtes fatigué ou blessé. Sans données de récupération et de VFC, vous devinez.", it:"Spingi forte ogni giorno e ti chiedi perché sei stanco o infortunato. Senza dati di recupero e HRV, vai a tentoni.", ja:"毎日全力で、なぜ疲れているのか・なぜ故障するのか分からない。回復とHRVのデータがなければ、ただの推測です。", ko:"매일 무리하면서 왜 피곤한지, 왜 다치는지 의아해합니다. 회복과 HRV 데이터가 없으면 그저 추측일 뿐입니다.", pt:"Você se esforça ao máximo todo dia e se pergunta por que está cansado ou lesionado. Sem dados de recuperação e VFC, é só chute.", ru:"Вы выкладываетесь каждый день и не понимаете, почему устали или получили травму. Без данных о восстановлении и ВСР это лишь догадки.", zh:"你每天拼尽全力，却不知为何疲惫或受伤。没有恢复和 HRV 数据，你只能靠猜。", ar:"تجتهد بقوة كل يوم وتتساءل لماذا تشعر بالتعب أو الإصابة. بدون بيانات التعافي وتقلب ضربات القلب، أنت تخمّن فقط." },
  "Consistency fades": { tr:"İstikrar kaybolur", de:"Die Beständigkeit schwindet", es:"La constancia se desvanece", fr:"La régularité s'effrite", it:"La costanza svanisce", ja:"継続が途切れる", ko:"꾸준함이 사라짐", pt:"A constância se perde", ru:"Постоянство угасает", zh:"坚持渐渐消失", ar:"يتلاشى الالتزام" },
  "Motivation dips, you miss a few days, and the habit quietly disappears. Nothing keeps you accountable.": { tr:"Motivasyon düşer, birkaç günü kaçırırsın ve alışkanlık sessizce kaybolur. Seni sorumlu tutan hiçbir şey yoktur.", de:"Die Motivation sinkt, du verpasst ein paar Tage, und die Gewohnheit verschwindet leise. Nichts hält dich in der Spur.", es:"La motivación baja, te saltas unos días y el hábito desaparece en silencio. Nada te mantiene comprometido.", fr:"La motivation baisse, vous sautez quelques jours, et l'habitude disparaît en silence. Rien ne vous tient responsable.", it:"La motivazione cala, salti qualche giorno e l'abitudine svanisce in silenzio. Niente ti tiene sulla retta via.", ja:"モチベーションが落ち、数日サボると、習慣は静かに消える。あなたを律してくれるものは何もない。", ko:"동기가 떨어지고 며칠 빠지면 습관은 조용히 사라집니다. 당신을 붙잡아 줄 것이 없습니다.", pt:"A motivação cai, você perde alguns dias e o hábito some em silêncio. Nada te mantém comprometido.", ru:"Мотивация падает, вы пропускаете пару дней, и привычка тихо исчезает. Ничто не держит вас в тонусе.", zh:"动力下降，你漏练几天，习惯便悄然消失。没有什么让你坚持下去。", ar:"يهبط الحماس، تفوّتك بضعة أيام، وتختفي العادة بهدوء. لا شيء يبقيك ملتزمًا." },

  // ── 02 Features ──
  "02 — Everything you need": { tr:"02 — İhtiyacın olan her şey", de:"02 — Alles, was du brauchst", es:"02 — Todo lo que necesitas", fr:"02 — Tout ce qu'il vous faut", it:"02 — Tutto ciò che ti serve", ja:"02 — 必要なすべて", ko:"02 — 필요한 모든 것", pt:"02 — Tudo o que você precisa", ru:"02 — Всё, что нужно", zh:"02 — 你需要的一切", ar:"02 — كل ما تحتاجه" },
  "Six tools. One app.": { tr:"Altı araç. Tek uygulama.", de:"Sechs Tools. Eine App.", es:"Seis herramientas. Una app.", fr:"Six outils. Une app.", it:"Sei strumenti. Un'app.", ja:"6つのツール、1つのアプリ。", ko:"여섯 가지 도구, 하나의 앱.", pt:"Seis ferramentas. Um app.", ru:"Шесть инструментов. Одно приложение.", zh:"六大工具，一个应用。", ar:"ست أدوات. تطبيق واحد." },
  "Each is useful on its own — and far more powerful when they all share the same data.": { tr:"Her biri tek başına faydalıdır — hepsi aynı veriyi paylaştığında çok daha güçlüdür.", de:"Jedes ist für sich nützlich — und weitaus stärker, wenn alle dieselben Daten teilen.", es:"Cada una es útil por sí sola — y mucho más potente cuando todas comparten los mismos datos.", fr:"Chacun est utile en soi — et bien plus puissant lorsqu'ils partagent les mêmes données.", it:"Ognuno è utile da solo — e molto più potente quando condividono gli stessi dati.", ja:"それぞれ単体でも役立ちますが、同じデータを共有するとさらに強力になります。", ko:"각각 단독으로도 유용하지만, 같은 데이터를 공유하면 훨씬 강력해집니다.", pt:"Cada uma é útil por si só — e muito mais poderosa quando todas compartilham os mesmos dados.", ru:"Каждый полезен сам по себе — и куда мощнее, когда все используют одни и те же данные.", zh:"每个单独都有用 — 当它们共享同一份数据时，则强大得多。", ar:"كل أداة مفيدة بمفردها — وأقوى بكثير عندما تشترك جميعها في البيانات نفسها." },
  "Workout Tracker": { tr:"<a class='feat-title-link' href='/workout-tracker/'>Antrenman Takibi</a>", de:"<a class='feat-title-link' href='/workout-tracker/'>Workout-Tracker</a>", es:"<a class='feat-title-link' href='/workout-tracker/'>Registro de entrenos</a>", fr:"<a class='feat-title-link' href='/workout-tracker/'>Suivi des séances</a>", it:"<a class='feat-title-link' href='/workout-tracker/'>Tracker allenamenti</a>", ja:"<a class='feat-title-link' href='/workout-tracker/'>ワークアウト記録</a>", ko:"<a class='feat-title-link' href='/workout-tracker/'>운동 추적</a>", pt:"<a class='feat-title-link' href='/workout-tracker/'>Registro de treinos</a>", ru:"<a class='feat-title-link' href='/workout-tracker/'>Трекер тренировок</a>", zh:"<a class='feat-title-link' href='/workout-tracker/'>训练记录</a>", ar:"<a class='feat-title-link' href='/workout-tracker/'>متتبّع التمارين</a>" },
  "Real-time GPS on a clean, distraction-free map with live pace, heart rate, elevation and splits. Finish with a shareable route card.": { tr:"Sade, dikkat dağıtmayan bir haritada gerçek zamanlı GPS; anlık tempo, nabız, yükseklik ve split'ler. Paylaşılabilir bir rota kartıyla bitir.", de:"Echtzeit-GPS auf einer klaren, ablenkungsfreien Karte mit Live-Pace, Herzfrequenz, Höhe und Splits. Zum Schluss eine teilbare Routenkarte.", es:"GPS en tiempo real en un mapa limpio y sin distracciones, con ritmo, frecuencia cardiaca, desnivel y parciales en vivo. Termina con una tarjeta de ruta para compartir.", fr:"GPS en temps réel sur une carte épurée et sans distraction, avec allure, fréquence cardiaque, dénivelé et splits en direct. Terminez par une carte d'itinéraire partageable.", it:"GPS in tempo reale su una mappa pulita e senza distrazioni, con passo, frequenza cardiaca, dislivello e parziali dal vivo. Concludi con una route card condivisibile.", ja:"すっきりと集中できる地図上でリアルタイムGPS。ペース、心拍、標高、スプリットをライブ表示。共有できるルートカードで締めくくり。", ko:"깔끔하고 방해 없는 지도 위의 실시간 GPS — 실시간 페이스, 심박수, 고도, 스플릿까지. 공유 가능한 루트 카드로 마무리하세요.", pt:"GPS em tempo real em um mapa limpo e sem distrações, com ritmo, frequência cardíaca, altimetria e parciais ao vivo. Termine com um cartão de rota para compartilhar.", ru:"GPS в реальном времени на чистой карте без отвлечений: темп, пульс, набор высоты и сплиты вживую. В конце — карточка маршрута, которой можно поделиться.", zh:"在简洁无干扰的地图上实时 GPS，实时显示配速、心率、海拔和分段。结束后生成可分享的路线卡。", ar:"GPS فوري على خريطة نظيفة وخالية من التشتيت، مع عرض حيّ للوتيرة ونبض القلب والارتفاع والمراحل. وفي النهاية بطاقة مسار قابلة للمشاركة." },
  "Recovery & HRV": { tr:"<a class='feat-title-link' href='/recovery-tracker/'>Toparlanma ve HRV</a>", de:"<a class='feat-title-link' href='/recovery-tracker/'>Erholung & HRV</a>", es:"<a class='feat-title-link' href='/recovery-tracker/'>Recuperación y HRV</a>", fr:"<a class='feat-title-link' href='/recovery-tracker/'>Récupération & VFC</a>", it:"<a class='feat-title-link' href='/recovery-tracker/'>Recupero e HRV</a>", ja:"<a class='feat-title-link' href='/recovery-tracker/'>回復とHRV</a>", ko:"<a class='feat-title-link' href='/recovery-tracker/'>회복 & HRV</a>", pt:"<a class='feat-title-link' href='/recovery-tracker/'>Recuperação e VFC</a>", ru:"<a class='feat-title-link' href='/recovery-tracker/'>Восстановление и ВСР</a>", zh:"<a class='feat-title-link' href='/recovery-tracker/'>恢复与 HRV</a>", ar:"<a class='feat-title-link' href='/recovery-tracker/'>التعافي وتقلب ضربات القلب</a>" },
  "A daily readiness score from your Apple Watch HRV, resting heart rate and sleep — so you know when to push and when to rest.": { tr:"Apple Watch HRV'n, dinlenme nabzın ve uykundan günlük bir hazırlık skoru — böylece ne zaman zorlanıp ne zaman dinleneceğini bilirsin.", de:"Ein täglicher Readiness-Score aus deiner Apple-Watch-HRV, Ruheherzfrequenz und Schlaf — damit du weißt, wann du Gas geben und wann du ruhen solltest.", es:"Una puntuación diaria de preparación a partir del HRV de tu Apple Watch, la frecuencia en reposo y el sueño — para saber cuándo exigirte y cuándo descansar.", fr:"Un score de forme quotidien à partir de la VFC de votre Apple Watch, de votre fréquence au repos et de votre sommeil — pour savoir quand pousser et quand récupérer.", it:"Un punteggio di prontezza giornaliero da HRV dell'Apple Watch, frequenza a riposo e sonno — così sai quando spingere e quando riposare.", ja:"Apple WatchのHRV、安静時心拍、睡眠から毎日のレディネススコアを算出 — 攻める日と休む日が分かります。", ko:"Apple Watch의 HRV, 안정 시 심박수, 수면을 바탕으로 한 매일의 준비도 점수 — 언제 밀어붙이고 언제 쉴지 알 수 있습니다.", pt:"Uma pontuação diária de prontidão a partir da VFC do seu Apple Watch, frequência em repouso e sono — para saber quando avançar e quando descansar.", ru:"Ежедневная оценка готовности по ВСР Apple Watch, пульсу покоя и сну — чтобы знать, когда ускориться, а когда отдохнуть.", zh:"根据 Apple Watch 的 HRV、静息心率和睡眠，生成每日就绪评分 — 让你知道何时发力、何时休息。", ar:"درجة جاهزية يومية من تقلب ضربات قلب Apple Watch ومعدل النبض أثناء الراحة والنوم — لتعرف متى تجتهد ومتى ترتاح." },
  "Sleep Tracking": { tr:"<a class='feat-title-link' href='/sleep-tracker/'>Uyku Takibi</a>", de:"<a class='feat-title-link' href='/sleep-tracker/'>Schlaf-Tracking</a>", es:"<a class='feat-title-link' href='/sleep-tracker/'>Seguimiento del sueño</a>", fr:"<a class='feat-title-link' href='/sleep-tracker/'>Suivi du sommeil</a>", it:"<a class='feat-title-link' href='/sleep-tracker/'>Monitoraggio del sonno</a>", ja:"<a class='feat-title-link' href='/sleep-tracker/'>睡眠トラッキング</a>", ko:"<a class='feat-title-link' href='/sleep-tracker/'>수면 추적</a>", pt:"<a class='feat-title-link' href='/sleep-tracker/'>Monitoramento do sono</a>", ru:"<a class='feat-title-link' href='/sleep-tracker/'>Отслеживание сна</a>", zh:"<a class='feat-title-link' href='/sleep-tracker/'>睡眠追踪</a>", ar:"<a class='feat-title-link' href='/sleep-tracker/'>تتبّع النوم</a>" },
  "Deep, REM and light stages every morning. See how training and nutrition affect the quality of your rest.": { tr:"Her sabah derin, REM ve hafif uyku evreleri. Antrenman ve beslenmenin dinlenme kaliteni nasıl etkilediğini gör.", de:"Tief-, REM- und Leichtschlafphasen jeden Morgen. Sieh, wie Training und Ernährung deine Schlafqualität beeinflussen.", es:"Fases profunda, REM y ligera cada mañana. Mira cómo el entreno y la nutrición afectan la calidad de tu descanso.", fr:"Phases profond, paradoxal et léger chaque matin. Voyez comment l'entraînement et la nutrition influent sur la qualité de votre repos.", it:"Fasi profonda, REM e leggera ogni mattina. Scopri come allenamento e nutrizione influenzano la qualità del riposo.", ja:"毎朝、深い・レム・浅い睡眠のステージを表示。トレーニングと栄養が休息の質にどう影響するかが分かります。", ko:"매일 아침 깊은·렘·얕은 수면 단계. 훈련과 영양이 휴식의 질에 어떤 영향을 주는지 확인하세요.", pt:"Fases profunda, REM e leve toda manhã. Veja como treino e nutrição afetam a qualidade do seu descanso.", ru:"Каждое утро — фазы глубокого, быстрого и лёгкого сна. Узнайте, как тренировки и питание влияют на качество отдыха.", zh:"每天早晨呈现深睡、REM 和浅睡阶段。看看训练与营养如何影响你的休息质量。", ar:"مراحل النوم العميق وREM والخفيف كل صباح. اطّلع على كيفية تأثير التمرين والتغذية في جودة راحتك." },
  "AI Nutrition": { tr:"Yapay Zekâ Beslenme", de:"KI-Ernährung", es:"Nutrición con IA", fr:"Nutrition par IA", it:"Nutrizione con IA", ja:"AI栄養管理", ko:"AI 영양", pt:"Nutrição com IA", ru:"ИИ-питание", zh:"AI 营养", ar:"التغذية بالذكاء الاصطناعي" },
  "Snap a photo of your plate and AI breaks down calories, protein, carbs and fat. Scan barcodes and set your own macro goals.": { tr:"Tabağının fotoğrafını çek, yapay zekâ kalori, protein, karbonhidrat ve yağı ayrıştırsın. Barkod tara ve kendi makro hedeflerini belirle.", de:"Mach ein Foto deines Tellers, und die KI schlüsselt Kalorien, Protein, Kohlenhydrate und Fett auf. Barcodes scannen und eigene Makroziele setzen.", es:"Haz una foto de tu plato y la IA desglosa calorías, proteína, carbohidratos y grasa. Escanea códigos de barras y fija tus propios objetivos de macros.", fr:"Photographiez votre assiette et l'IA détaille calories, protéines, glucides et lipides. Scannez les codes-barres et fixez vos objectifs de macros.", it:"Fotografa il tuo piatto e l'IA scompone calorie, proteine, carboidrati e grassi. Scansiona i codici a barre e imposta i tuoi obiettivi di macro.", ja:"皿を撮影すれば、AIがカロリー・タンパク質・炭水化物・脂質を分解。バーコードを読み取り、自分のマクロ目標も設定できます。", ko:"접시를 사진으로 찍으면 AI가 칼로리·단백질·탄수화물·지방을 분석합니다. 바코드를 스캔하고 나만의 매크로 목표를 설정하세요.", pt:"Tire uma foto do seu prato e a IA detalha calorias, proteína, carboidratos e gordura. Escaneie códigos de barras e defina suas metas de macros.", ru:"Сфотографируйте тарелку — ИИ разложит калории, белки, углеводы и жиры. Сканируйте штрихкоды и задавайте свои цели по макросам.", zh:"拍下你的餐盘，AI 即可拆解卡路里、蛋白质、碳水和脂肪。扫描条形码并设定你自己的宏量目标。", ar:"التقط صورة لطبقك ويحلّل الذكاء الاصطناعي السعرات والبروتين والكربوهيدرات والدهون. امسح الباركود وحدّد أهداف الماكروز الخاصة بك." },
  "AI Coach": { tr:"Yapay Zekâ Koç", de:"KI-Coach", es:"Coach con IA", fr:"Coach IA", it:"Coach IA", ja:"AIコーチ", ko:"AI 코치", pt:"Coach com IA", ru:"ИИ-тренер", zh:"AI 教练", ar:"مدرّب الذكاء الاصطناعي" },
  "Ask anything. Your coach reads your real recovery, training load and goals, then answers with your numbers — not generic tips.": { tr:"Her şeyi sor. Koçun gerçek toparlanmanı, antrenman yükünü ve hedeflerini okur, sonra genel tavsiyelerle değil senin rakamlarınla yanıt verir.", de:"Frag alles. Dein Coach liest deine echte Erholung, Trainingslast und Ziele und antwortet mit deinen Zahlen — keine generischen Tipps.", es:"Pregunta lo que quieras. Tu coach lee tu recuperación real, tu carga de entreno y tus metas, y responde con tus números — no con consejos genéricos.", fr:"Demandez n'importe quoi. Votre coach lit votre récupération réelle, votre charge d'entraînement et vos objectifs, puis répond avec vos chiffres — pas des conseils génériques.", it:"Chiedi qualsiasi cosa. Il tuo coach legge recupero reale, carico di allenamento e obiettivi, poi risponde con i tuoi numeri — non consigli generici.", ja:"何でも質問を。コーチはあなたの実際の回復・トレーニング負荷・目標を読み取り、一般論ではなくあなたの数値で答えます。", ko:"무엇이든 물어보세요. 코치는 실제 회복, 훈련 부하, 목표를 읽고 일반적인 팁이 아니라 당신의 수치로 답합니다.", pt:"Pergunte qualquer coisa. Seu coach lê sua recuperação real, carga de treino e metas, e responde com os seus números — não dicas genéricas.", ru:"Спрашивайте что угодно. Тренер читает ваше реальное восстановление, нагрузку и цели и отвечает вашими цифрами, а не общими советами.", zh:"尽管发问。你的教练读取你真实的恢复、训练负荷和目标，用你的数据作答 — 而非泛泛建议。", ar:"اسأل أي شيء. يقرأ مدرّبك تعافيك الحقيقي وحِمل تدريبك وأهدافك، ثم يجيب بأرقامك — لا بنصائح عامة." },
  "Community": { tr:"<a class='feat-title-link' href='/community/'>Topluluk</a>", de:"<a class='feat-title-link' href='/community/'>Community</a>", es:"<a class='feat-title-link' href='/community/'>Comunidad</a>", fr:"<a class='feat-title-link' href='/community/'>Communauté</a>", it:"<a class='feat-title-link' href='/community/'>Comunità</a>", ja:"<a class='feat-title-link' href='/community/'>コミュニティ</a>", ko:"<a class='feat-title-link' href='/community/'>커뮤니티</a>", pt:"<a class='feat-title-link' href='/community/'>Comunidade</a>", ru:"<a class='feat-title-link' href='/community/'>Сообщество</a>", zh:"<a class='feat-title-link' href='/community/'>社区</a>", ar:"<a class='feat-title-link' href='/community/'>المجتمع</a>" },
  "Follow friends, react to their workouts, join challenges and share your route card in one tap. Stay accountable together.": { tr:"Arkadaşlarını takip et, antrenmanlarına tepki ver, meydan okumalara katıl ve rota kartını tek dokunuşla paylaş. Birlikte sorumlu kalın.", de:"Folge Freunden, reagiere auf ihre Workouts, mach bei Challenges mit und teile deine Routenkarte mit einem Tipp. Bleibt gemeinsam dran.", es:"Sigue a tus amigos, reacciona a sus entrenos, únete a retos y comparte tu tarjeta de ruta con un toque. Manteneos comprometidos juntos.", fr:"Suivez vos amis, réagissez à leurs séances, rejoignez des défis et partagez votre carte d'itinéraire en un tap. Restez motivés ensemble.", it:"Segui gli amici, reagisci ai loro allenamenti, partecipa alle sfide e condividi la tua route card con un tap. Restate motivati insieme.", ja:"友達をフォローし、ワークアウトにリアクションし、チャレンジに参加し、ルートカードをワンタップで共有。みんなで続ける。", ko:"친구를 팔로우하고, 운동에 반응하고, 챌린지에 참여하고, 루트 카드를 한 번에 공유하세요. 함께 꾸준함을 유지하세요.", pt:"Siga amigos, reaja aos treinos deles, participe de desafios e compartilhe seu cartão de rota com um toque. Mantenham-se firmes juntos.", ru:"Подписывайтесь на друзей, реагируйте на их тренировки, участвуйте в челленджах и делитесь карточкой маршрута одним касанием. Держитесь вместе.", zh:"关注好友、为他们的训练点赞、参加挑战，一键分享你的路线卡。一起保持坚持。", ar:"تابع أصدقاءك، وتفاعل مع تمارينهم، وانضمّ إلى التحديات، وشارك بطاقة مسارك بنقرة واحدة. حافظوا على الالتزام معًا." },
  "Explore →": { tr:"Keşfet →", de:"Entdecken →", es:"Explorar →", fr:"Découvrir →", it:"Esplora →", ja:"詳しく見る →", ko:"살펴보기 →", pt:"Explorar →", ru:"Подробнее →", zh:"了解更多 →", ar:"استكشف →" },
  "See all →": { tr:"Tümünü gör →", de:"Alle ansehen →", es:"Ver todo →", fr:"Tout voir →", it:"Vedi tutto →", ja:"すべて見る →", ko:"전체 보기 →", pt:"Ver tudo →", ru:"Смотреть всё →", zh:"查看全部 →", ar:"عرض الكل →" },
  "Meet the coach →": { tr:"Koçla tanış →", de:"Coach kennenlernen →", es:"Conoce al coach →", fr:"Rencontrer le coach →", it:"Scopri il coach →", ja:"コーチを見る →", ko:"코치 만나기 →", pt:"Conheça o coach →", ru:"Знакомство с тренером →", zh:"认识教练 →", ar:"تعرّف على المدرّب →" },

  // ── 03 Showcase ──
  "03 — The app": { tr:"03 — Uygulama", de:"03 — Die App", es:"03 — La app", fr:"03 — L'app", it:"03 — L'app", ja:"03 — アプリ", ko:"03 — 앱", pt:"03 — O app", ru:"03 — Приложение", zh:"03 — 应用", ar:"03 — التطبيق" },
  "Designed to be glanced at": { tr:"Bir bakışta anlaşılacak şekilde tasarlandı", de:"Für den schnellen Blick gemacht", es:"Diseñada para una mirada rápida", fr:"Conçue pour un coup d'œil", it:"Progettata per un'occhiata", ja:"ひと目で分かる設計", ko:"한눈에 보도록 설계", pt:"Projetada para um olhar rápido", ru:"Создано, чтобы взглянуть на ходу", zh:"为一瞥而设计", ar:"مصمّم لنظرة سريعة" },
  "Open it, get your answer, get on with your day. Every screen leads with the one number that matters — readiness, pace, calories left, tonight's sleep — and hides the rest until you ask.": { tr:"Aç, cevabını al, gününe devam et. Her ekran önemli olan tek rakamla başlar — hazırlık, tempo, kalan kalori, bu geceki uyku — gerisini sen sorana kadar gizler.", de:"Öffnen, Antwort bekommen, weitermachen. Jeder Screen beginnt mit der einen wichtigen Zahl — Readiness, Pace, verbleibende Kalorien, Schlaf heute Nacht — und verbirgt den Rest, bis du fragst.", es:"Ábrela, obtén tu respuesta y sigue con tu día. Cada pantalla muestra primero el número que importa — preparación, ritmo, calorías restantes, el sueño de esta noche — y oculta el resto hasta que preguntes.", fr:"Ouvrez, obtenez votre réponse, poursuivez votre journée. Chaque écran met en avant le seul chiffre qui compte — forme, allure, calories restantes, sommeil de la nuit — et cache le reste jusqu'à votre demande.", it:"Aprila, ottieni la risposta, vai avanti con la giornata. Ogni schermata mostra prima il numero che conta — prontezza, passo, calorie rimaste, sonno di stanotte — e nasconde il resto finché non chiedi.", ja:"開いて、答えを得て、一日に戻る。各画面は大事な数字を一つだけ前面に — レディネス、ペース、残りカロリー、今夜の睡眠 — 残りは尋ねるまで隠します。", ko:"열고, 답을 얻고, 일상으로. 모든 화면은 중요한 숫자 하나를 먼저 보여줍니다 — 준비도, 페이스, 남은 칼로리, 오늘 밤 수면 — 나머지는 물어볼 때까지 숨깁니다.", pt:"Abra, obtenha sua resposta e siga seu dia. Cada tela mostra primeiro o número que importa — prontidão, ritmo, calorias restantes, o sono desta noite — e esconde o resto até você perguntar.", ru:"Открыли, получили ответ, вернулись к делам. Каждый экран показывает одну важную цифру — готовность, темп, остаток калорий, сон этой ночи — а остальное скрывает, пока не спросите.", zh:"打开、得到答案、继续你的一天。每个界面只突出最重要的那个数字 — 就绪度、配速、剩余卡路里、今晚睡眠 — 其余内容在你需要时才显示。", ar:"افتحه، احصل على إجابتك، وتابع يومك. تبدأ كل شاشة بالرقم الوحيد المهم — الجاهزية، الوتيرة، السعرات المتبقية، نوم هذه الليلة — وتُخفي الباقي حتى تسأل." },
  "One dashboard for training, recovery and nutrition": { tr:"<strong>Tek bir pano</strong> — antrenman, toparlanma ve beslenme için", de:"<strong>Ein Dashboard</strong> für Training, Erholung und Ernährung", es:"<strong>Un solo panel</strong> para entreno, recuperación y nutrición", fr:"<strong>Un seul tableau de bord</strong> pour l'entraînement, la récupération et la nutrition", it:"<strong>Un'unica dashboard</strong> per allenamento, recupero e nutrizione", ja:"トレーニング・回復・栄養を<strong>1つのダッシュボード</strong>で", ko:"훈련·회복·영양을 위한 <strong>하나의 대시보드</strong>", pt:"<strong>Um painel</strong> para treino, recuperação e nutrição", ru:"<strong>Одна панель</strong> для тренировок, восстановления и питания", zh:"训练、恢复与营养，<strong>一个仪表盘</strong>", ar:"<strong>لوحة واحدة</strong> للتمرين والتعافي والتغذية" },
  "Distraction-free GPS with live pace and clean route maps": { tr:"<strong>Dikkat dağıtmayan GPS</strong> — anlık tempo ve sade rota haritalarıyla", de:"<strong>Ablenkungsfreies GPS</strong> mit Live-Pace und klaren Routenkarten", es:"<strong>GPS sin distracciones</strong> con ritmo en vivo y mapas de ruta limpios", fr:"<strong>GPS sans distraction</strong> avec allure en direct et cartes d'itinéraire épurées", it:"<strong>GPS senza distrazioni</strong> con passo dal vivo e mappe pulite", ja:"<strong>集中できるGPS</strong> — ライブペースとすっきりしたルートマップ", ko:"<strong>방해 없는 GPS</strong> — 실시간 페이스와 깔끔한 루트 지도", pt:"<strong>GPS sem distrações</strong> com ritmo ao vivo e mapas de rota limpos", ru:"<strong>GPS без отвлечений</strong> с темпом в реальном времени и чистыми картами маршрутов", zh:"<strong>无干扰 GPS</strong>，实时配速与简洁路线地图", ar:"<strong>GPS بلا تشتيت</strong> مع وتيرة حية وخرائط مسار نظيفة" },
  "Recovery first — your readiness score, front and centre": { tr:"<strong>Önce toparlanma</strong> — hazırlık skorun, en önde ve merkezde", de:"<strong>Erholung zuerst</strong> — dein Readiness-Score, klar im Mittelpunkt", es:"<strong>La recuperación primero</strong> — tu puntuación de preparación, en primer plano", fr:"<strong>La récupération d'abord</strong> — votre score de forme, bien en évidence", it:"<strong>Prima il recupero</strong> — il tuo punteggio di prontezza, in primo piano", ja:"<strong>まず回復</strong> — レディネススコアを真っ先に中央に", ko:"<strong>회복이 먼저</strong> — 준비도 점수를 가장 앞 중앙에", pt:"<strong>Recuperação primeiro</strong> — sua pontuação de prontidão em destaque", ru:"<strong>Сначала восстановление</strong> — ваша оценка готовности на первом плане", zh:"<strong>恢复优先</strong> — 就绪评分，置于正中", ar:"<strong>التعافي أولًا</strong> — درجة جاهزيتك في الصدارة" },

  // ── 04 How it works ──
  "04 — How it works": { tr:"04 — Nasıl çalışır", de:"04 — So funktioniert's", es:"04 — Cómo funciona", fr:"04 — Comment ça marche", it:"04 — Come funziona", ja:"04 — 使い方", ko:"04 — 작동 방식", pt:"04 — Como funciona", ru:"04 — Как это работает", zh:"04 — 工作原理", ar:"04 — كيف يعمل" },
  "Track → Understand → Improve": { tr:"Takip Et → Anla → Geliş", de:"Erfassen → Verstehen → Verbessern", es:"Registra → Entiende → Mejora", fr:"Suivre → Comprendre → Progresser", it:"Monitora → Capisci → Migliora", ja:"記録 → 理解 → 改善", ko:"기록 → 이해 → 개선", pt:"Registre → Entenda → Melhore", ru:"Отслеживай → Понимай → Улучшай", zh:"记录 → 理解 → 提升", ar:"تتبّع → افهم → تحسّن" },
  "Up and running in minutes. Start with a free trial. Works with any smartwatch that syncs to Apple Health.": { tr:"Dakikalar içinde hazır. Ücretsiz denemeyle başla. Apple Health ile senkronize olan her akıllı saatle çalışır.", de:"In Minuten startklar. Beginne mit einer kostenlosen Testphase. Funktioniert mit jeder Smartwatch, die mit Apple Health synchronisiert.", es:"Listo en minutos. Empieza con una prueba gratuita. Funciona con cualquier smartwatch que sincronice con Apple Health.", fr:"Opérationnel en quelques minutes. Commencez par un essai gratuit. Compatible avec toute montre connectée synchronisée à Apple Health.", it:"Pronto in pochi minuti. Inizia con una prova gratuita. Funziona con qualsiasi smartwatch che si sincronizza con Apple Health.", ja:"数分でスタート。無料トライアルから始められます。Apple Healthと同期するスマートウォッチに対応。", ko:"몇 분이면 시작. 무료 체험으로 시작하세요. Apple Health와 동기화되는 모든 스마트워치와 호환됩니다.", pt:"Pronto em minutos. Comece com um teste grátis. Funciona com qualquer smartwatch que sincroniza com o Apple Health.", ru:"Готово за минуты. Начните с бесплатного пробного периода. Работает с любыми часами, синхронизирующимися с Apple Health.", zh:"几分钟即可上手。从免费试用开始。兼容任何同步到 Apple Health 的智能手表。", ar:"جاهز خلال دقائق. ابدأ بتجربة مجانية. يعمل مع أي ساعة ذكية تتزامن مع Apple Health." },
  "Track": { tr:"Takip Et", de:"Erfassen", es:"Registra", fr:"Suivre", it:"Monitora", ja:"記録", ko:"기록", pt:"Registre", ru:"Отслеживай", zh:"记录", ar:"تتبّع" },
  "Record GPS workouts in real time, or let MyVitality pull your runs, rides, sleep and heart rate automatically from Apple Health.": { tr:"GPS antrenmanlarını gerçek zamanlı kaydet ya da MyVitality koşularını, bisikletlerini, uykunu ve nabzını Apple Health'ten otomatik çeksin.", de:"Zeichne GPS-Workouts in Echtzeit auf, oder lass MyVitality deine Läufe, Fahrten, Schlaf und Herzfrequenz automatisch aus Apple Health holen.", es:"Graba entrenos con GPS en tiempo real, o deja que MyVitality importe tus carreras, salidas, sueño y frecuencia cardiaca desde Apple Health.", fr:"Enregistrez vos séances GPS en temps réel, ou laissez MyVitality importer vos courses, sorties, sommeil et fréquence cardiaque depuis Apple Health.", it:"Registra allenamenti GPS in tempo reale, oppure lascia che MyVitality importi corse, uscite, sonno e frequenza cardiaca da Apple Health.", ja:"GPSワークアウトをリアルタイムで記録、またはMyVitalityがApple Healthからランニング・ライド・睡眠・心拍を自動取得。", ko:"GPS 운동을 실시간으로 기록하거나, MyVitality가 Apple Health에서 달리기·라이딩·수면·심박수를 자동으로 가져오게 하세요.", pt:"Grave treinos com GPS em tempo real, ou deixe o MyVitality importar suas corridas, pedais, sono e frequência cardíaca do Apple Health.", ru:"Записывайте GPS-тренировки в реальном времени или позвольте MyVitality автоматически подтягивать пробежки, заезды, сон и пульс из Apple Health.", zh:"实时记录 GPS 训练，或让 MyVitality 从 Apple Health 自动获取你的跑步、骑行、睡眠和心率。", ar:"سجّل تمارين GPS فوريًا، أو دع MyVitality يسحب جلسات الجري والدراجة والنوم ونبض القلب تلقائيًا من Apple Health." },
  "Understand": { tr:"Anla", de:"Verstehen", es:"Entiende", fr:"Comprendre", it:"Capisci", ja:"理解", ko:"이해", pt:"Entenda", ru:"Понимай", zh:"理解", ar:"افهم" },
  "Wake up to a recovery score from your HRV and sleep. See your training load, trends and what's actually moving the needle.": { tr:"HRV ve uykundan gelen bir toparlanma skoruyla uyan. Antrenman yükünü, eğilimleri ve asıl fark yaratan şeyi gör.", de:"Wach auf mit einem Erholungs-Score aus HRV und Schlaf. Sieh deine Trainingslast, Trends und was wirklich etwas bewegt.", es:"Despierta con una puntuación de recuperación a partir de tu HRV y sueño. Mira tu carga de entreno, tendencias y lo que de verdad marca la diferencia.", fr:"Réveillez-vous avec un score de récupération issu de votre VFC et de votre sommeil. Voyez votre charge d'entraînement, vos tendances et ce qui fait vraiment la différence.", it:"Svegliati con un punteggio di recupero da HRV e sonno. Vedi il carico di allenamento, le tendenze e ciò che fa davvero la differenza.", ja:"HRVと睡眠から算出される回復スコアで目覚める。トレーニング負荷、傾向、本当に効いている要因が分かります。", ko:"HRV와 수면에서 산출된 회복 점수와 함께 아침을 맞으세요. 훈련 부하, 추세, 실제로 효과를 내는 요인을 확인하세요.", pt:"Acorde com uma pontuação de recuperação a partir da sua VFC e sono. Veja sua carga de treino, tendências e o que realmente faz diferença.", ru:"Просыпайтесь с оценкой восстановления на основе ВСР и сна. Смотрите нагрузку, тренды и то, что действительно даёт результат.", zh:"醒来即获得基于 HRV 和睡眠的恢复评分。查看你的训练负荷、趋势，以及真正起作用的因素。", ar:"استيقظ على درجة تعافٍ مستمدة من تقلب ضربات قلبك ونومك. اطّلع على حِمل تدريبك واتجاهاتك وما يُحدث فرقًا فعليًا." },
  "Improve": { tr:"Geliş", de:"Verbessern", es:"Mejora", fr:"Progresser", it:"Migliora", ja:"改善", ko:"개선", pt:"Melhore", ru:"Улучшай", zh:"提升", ar:"تحسّن" },
  "Ask your AI coach what to do today, log your meals, hit your streak and stay consistent with friends cheering you on.": { tr:"Yapay zekâ koçuna bugün ne yapacağını sor, öğünlerini kaydet, serini sürdür ve seni destekleyen arkadaşlarınla istikrarlı kal.", de:"Frag deinen KI-Coach, was heute ansteht, logge deine Mahlzeiten, halte deine Serie und bleib dran — mit Freunden, die dich anfeuern.", es:"Pregunta a tu coach con IA qué hacer hoy, registra tus comidas, mantén tu racha y sé constante con amigos que te animan.", fr:"Demandez à votre coach IA quoi faire aujourd'hui, enregistrez vos repas, tenez votre série et restez régulier avec des amis qui vous encouragent.", it:"Chiedi al tuo coach IA cosa fare oggi, registra i pasti, mantieni la tua streak e resta costante con gli amici che ti incoraggiano.", ja:"AIコーチに今日すべきことを聞き、食事を記録し、連続記録を伸ばし、応援してくれる友達と一緒に継続。", ko:"AI 코치에게 오늘 할 일을 묻고, 식사를 기록하고, 연속 기록을 이어가며, 응원해 주는 친구들과 함께 꾸준함을 유지하세요.", pt:"Pergunte ao seu coach com IA o que fazer hoje, registre suas refeições, mantenha sua sequência e seja constante com amigos torcendo por você.", ru:"Спросите ИИ-тренера, что делать сегодня, отмечайте приёмы пищи, держите серию и будьте последовательны с поддержкой друзей.", zh:"问问你的 AI 教练今天该做什么，记录三餐，延续你的连续打卡，在好友的加油声中保持坚持。", ar:"اسأل مدرّب الذكاء الاصطناعي عمّا تفعله اليوم، وسجّل وجباتك، وحافظ على سلسلتك، واستمر بثبات مع أصدقاء يشجّعونك." },

  // ── 05 AI coach ──
  "05 — AI coach": { tr:"05 — Yapay zekâ koç", de:"05 — KI-Coach", es:"05 — Coach con IA", fr:"05 — Coach IA", it:"05 — Coach IA", ja:"05 — AIコーチ", ko:"05 — AI 코치", pt:"05 — Coach com IA", ru:"05 — ИИ-тренер", zh:"05 — AI 教练", ar:"05 — مدرّب الذكاء الاصطناعي" },
  "A coach that knows your data": { tr:"Verilerini bilen bir koç", de:"Ein Coach, der deine Daten kennt", es:"Un coach que conoce tus datos", fr:"Un coach qui connaît vos données", it:"Un coach che conosce i tuoi dati", ja:"あなたのデータを知るコーチ", ko:"당신의 데이터를 아는 코치", pt:"Um coach que conhece seus dados", ru:"Тренер, который знает ваши данные", zh:"懂你数据的教练", ar:"مدرّب يعرف بياناتك" },
  "Ask anything. MyVitality's coach reads your real recovery, training load, recent runs and goals — then answers with your numbers, not canned advice.": { tr:"Her şeyi sor. MyVitality'nin koçu gerçek toparlanmanı, antrenman yükünü, son koşularını ve hedeflerini okur — sonra hazır tavsiyelerle değil senin rakamlarınla yanıt verir.", de:"Frag alles. Der Coach von MyVitality liest deine echte Erholung, Trainingslast, letzten Läufe und Ziele — und antwortet mit deinen Zahlen, nicht mit Standardrat.", es:"Pregunta lo que quieras. El coach de MyVitality lee tu recuperación real, tu carga de entreno, tus carreras recientes y tus metas — y responde con tus números, no con consejos enlatados.", fr:"Demandez n'importe quoi. Le coach de MyVitality lit votre récupération réelle, votre charge, vos courses récentes et vos objectifs — puis répond avec vos chiffres, pas des conseils tout faits.", it:"Chiedi qualsiasi cosa. Il coach di MyVitality legge recupero reale, carico, corse recenti e obiettivi — poi risponde con i tuoi numeri, non consigli preconfezionati.", ja:"何でも質問を。MyVitalityのコーチはあなたの実際の回復・トレーニング負荷・最近のラン・目標を読み取り、決まり文句ではなくあなたの数値で答えます。", ko:"무엇이든 물어보세요. MyVitality 코치는 실제 회복, 훈련 부하, 최근 달리기, 목표를 읽고 판에 박힌 조언이 아니라 당신의 수치로 답합니다.", pt:"Pergunte qualquer coisa. O coach do MyVitality lê sua recuperação real, carga de treino, corridas recentes e metas — e responde com os seus números, não conselhos prontos.", ru:"Спрашивайте что угодно. Тренер MyVitality читает ваше реальное восстановление, нагрузку, недавние пробежки и цели — и отвечает вашими цифрами, а не шаблонными советами.", zh:"尽管发问。MyVitality 的教练读取你真实的恢复、训练负荷、近期跑步和目标 — 用你的数据作答，而非套话。", ar:"اسأل أي شيء. يقرأ مدرّب MyVitality تعافيك الحقيقي وحِمل تدريبك وجلسات جريك الأخيرة وأهدافك — ثم يجيب بأرقامك، لا بنصائح جاهزة." },
  "Knows your HRV, sleep, training load & goals": { tr:"<strong>HRV'ni, uykunu, antrenman yükünü ve hedeflerini bilir</strong>", de:"<strong>Kennt deine HRV, Schlaf, Trainingslast & Ziele</strong>", es:"<strong>Conoce tu HRV, sueño, carga de entreno y metas</strong>", fr:"<strong>Connaît votre VFC, sommeil, charge & objectifs</strong>", it:"<strong>Conosce HRV, sonno, carico e obiettivi</strong>", ja:"<strong>HRV・睡眠・トレーニング負荷・目標を把握</strong>", ko:"<strong>HRV, 수면, 훈련 부하 & 목표를 파악</strong>", pt:"<strong>Conhece sua VFC, sono, carga de treino e metas</strong>", ru:"<strong>Знает вашу ВСР, сон, нагрузку и цели</strong>", zh:"<strong>了解你的 HRV、睡眠、训练负荷与目标</strong>", ar:"<strong>يعرف تقلب ضربات قلبك ونومك وحِمل تدريبك وأهدافك</strong>" },
  "Race-time predictions and taper guidance for your next event": { tr:"<strong>Yarış zamanı tahminleri ve taper rehberi</strong> — bir sonraki yarışın için", de:"<strong>Wettkampfzeit-Prognosen und Taper-Empfehlungen</strong> für dein nächstes Event", es:"<strong>Predicciones de tiempo de carrera y guía de tapering</strong> para tu próxima prueba", fr:"<strong>Prédictions de temps de course et conseils d'affûtage</strong> pour votre prochaine épreuve", it:"<strong>Previsioni del tempo di gara e guida al tapering</strong> per il tuo prossimo evento", ja:"次のレースに向けた<strong>レースタイム予測とテーパリングの指針</strong>", ko:"다음 대회를 위한 <strong>레이스 타임 예측과 테이퍼링 가이드</strong>", pt:"<strong>Previsões de tempo de prova e orientação de tapering</strong> para sua próxima competição", ru:"<strong>Прогноз времени на гонку и план тейпера</strong> к вашему следующему старту", zh:"为你的下一场比赛提供<strong>成绩预测与减量训练指导</strong>", ar:"<strong>توقّعات زمن السباق وإرشادات التخفيف</strong> لحدثك القادم" },
  "Grounded in your data — never generic, copy-paste tips": { tr:"<strong>Verilerine dayalı</strong> — asla genel, kopyala-yapıştır tavsiyeler değil", de:"<strong>Auf deinen Daten basierend</strong> — nie generische Copy-Paste-Tipps", es:"<strong>Basado en tus datos</strong> — nunca consejos genéricos de copiar y pegar", fr:"<strong>Fondé sur vos données</strong> — jamais des conseils génériques copiés-collés", it:"<strong>Basato sui tuoi dati</strong> — mai consigli generici copia-incolla", ja:"<strong>あなたのデータに基づく</strong> — ありきたりのコピペ助言ではありません", ko:"<strong>당신의 데이터에 근거</strong> — 복붙식 일반 조언이 아닙니다", pt:"<strong>Baseado nos seus dados</strong> — nunca dicas genéricas de copiar e colar", ru:"<strong>Опирается на ваши данные</strong> — никаких шаблонных советов", zh:"<strong>基于你的数据</strong> — 绝非千篇一律的复制粘贴建议", ar:"<strong>مبني على بياناتك</strong> — وليس نصائح عامة منسوخة" },
  "Just ask in plain language, any time of day": { tr:"<strong>Günün her saati, sade bir dille sor</strong>", de:"<strong>Frag einfach in klarer Sprache, zu jeder Tageszeit</strong>", es:"<strong>Solo pregunta en lenguaje natural, a cualquier hora</strong>", fr:"<strong>Demandez simplement, en langage naturel, à tout moment</strong>", it:"<strong>Chiedi in linguaggio naturale, a qualsiasi ora</strong>", ja:"<strong>いつでも、普通の言葉で聞くだけ</strong>", ko:"<strong>언제든 평범한 말로 물어보세요</strong>", pt:"<strong>Basta perguntar em linguagem natural, a qualquer hora</strong>", ru:"<strong>Просто спросите обычными словами в любое время</strong>", zh:"<strong>随时用日常语言提问即可</strong>", ar:"<strong>اسأل بلغة عادية في أي وقت من اليوم</strong>" },

  // ── 06 Why / comparison ──
  "06 — Why MyVitality": { tr:"06 — Neden MyVitality", de:"06 — Warum MyVitality", es:"06 — Por qué MyVitality", fr:"06 — Pourquoi MyVitality", it:"06 — Perché MyVitality", ja:"06 — MyVitalityを選ぶ理由", ko:"06 — MyVitality를 선택하는 이유", pt:"06 — Por que MyVitality", ru:"06 — Почему MyVitality", zh:"06 — 为何选择 MyVitality", ar:"06 — لماذا MyVitality" },
  "Made to be used every day": { tr:"Her gün kullanılmak için yapıldı", de:"Gemacht für jeden Tag", es:"Hecha para usarse cada día", fr:"Conçue pour un usage quotidien", it:"Fatta per essere usata ogni giorno", ja:"毎日使うために作られた", ko:"매일 쓰도록 만들었습니다", pt:"Feita para usar todos os dias", ru:"Создано для ежедневного использования", zh:"为每天使用而打造", ar:"صُمّم لتستخدمه كل يوم" },
  "Not another dashboard you check once and forget. Three ideas keep you coming back.": { tr:"Bir kez bakıp unuttuğun bir pano değil. Üç fikir geri dönmeni sağlar.", de:"Kein weiteres Dashboard, das du einmal checkst und vergisst. Drei Ideen holen dich zurück.", es:"No es otro panel que miras una vez y olvidas. Tres ideas te hacen volver.", fr:"Pas un énième tableau de bord que l'on consulte une fois et oublie. Trois idées vous font revenir.", it:"Non l'ennesima dashboard che guardi una volta e dimentichi. Tre idee ti fanno tornare.", ja:"一度見て忘れる、よくあるダッシュボードではありません。3つの工夫が、また開きたくさせます。", ko:"한 번 보고 잊는 또 하나의 대시보드가 아닙니다. 세 가지 아이디어가 계속 돌아오게 합니다.", pt:"Não é mais um painel que você olha uma vez e esquece. Três ideias fazem você voltar.", ru:"Это не очередная панель, в которую заглянул раз и забыл. Три идеи заставляют возвращаться.", zh:"不是又一个看一次就忘的仪表盘。三个理念让你一再回来。", ar:"ليست لوحة أخرى تنظر إليها مرة وتنساها. ثلاث أفكار تجعلك تعود دائمًا." },
  "One app, not five": { tr:"Beş değil, tek uygulama", de:"Eine App, nicht fünf", es:"Una app, no cinco", fr:"Une app, pas cinq", it:"Un'app, non cinque", ja:"5つではなく、1つのアプリ", ko:"다섯 개가 아닌, 하나의 앱", pt:"Um app, não cinco", ru:"Одно приложение вместо пяти", zh:"一个应用，而非五个", ar:"تطبيق واحد، لا خمسة" },
  "Training, recovery, sleep and nutrition finally live in one place — so the connections between them are obvious.": { tr:"Antrenman, toparlanma, uyku ve beslenme nihayet tek yerde — böylece aralarındaki bağlantılar apaçık.", de:"Training, Erholung, Schlaf und Ernährung leben endlich an einem Ort — so sind die Zusammenhänge offensichtlich.", es:"Entreno, recuperación, sueño y nutrición por fin en un solo lugar — así las conexiones entre ellos son evidentes.", fr:"Entraînement, récupération, sommeil et nutrition enfin au même endroit — les liens entre eux deviennent évidents.", it:"Allenamento, recupero, sonno e nutrizione finalmente in un solo posto — così i collegamenti sono evidenti.", ja:"トレーニング・回復・睡眠・栄養がついに一か所に — だからつながりが一目で分かります。", ko:"훈련·회복·수면·영양이 마침내 한곳에 — 그래서 그 연결이 분명해집니다.", pt:"Treino, recuperação, sono e nutrição finalmente em um só lugar — assim as conexões entre eles ficam óbvias.", ru:"Тренировки, восстановление, сон и питание наконец в одном месте — связи между ними очевидны.", zh:"训练、恢复、睡眠与营养终于汇于一处 — 它们之间的关联一目了然。", ar:"التمرين والتعافي والنوم والتغذية أخيرًا في مكان واحد — فتصبح الروابط بينها واضحة." },
  "Decisions, not data": { tr:"Veri değil, kararlar", de:"Entscheidungen, keine Daten", es:"Decisiones, no datos", fr:"Des décisions, pas des données", it:"Decisioni, non dati", ja:"データではなく、判断を", ko:"데이터가 아닌, 결정", pt:"Decisões, não dados", ru:"Решения, а не данные", zh:"给你决策，而非数据", ar:"قرارات، لا بيانات" },
  "A recovery score and an AI coach read your numbers and turn them into a clear answer: push today, or recover.": { tr:"Bir toparlanma skoru ve yapay zekâ koç, rakamlarını okuyup net bir cevaba dönüştürür: bugün zorla ya da dinlen.", de:"Ein Erholungs-Score und ein KI-Coach lesen deine Zahlen und machen daraus eine klare Antwort: heute Gas geben oder erholen.", es:"Una puntuación de recuperación y un coach con IA leen tus números y los convierten en una respuesta clara: hoy exígete o recupérate.", fr:"Un score de récupération et un coach IA lisent vos chiffres et les transforment en réponse claire : pousser aujourd'hui ou récupérer.", it:"Un punteggio di recupero e un coach IA leggono i tuoi numeri e li trasformano in una risposta chiara: oggi spingi o recupera.", ja:"回復スコアとAIコーチがあなたの数値を読み、明確な答えに変えます — 今日は攻めるか、休むか。", ko:"회복 점수와 AI 코치가 당신의 수치를 읽어 명확한 답으로 바꿉니다: 오늘 밀어붙일지, 쉴지.", pt:"Uma pontuação de recuperação e um coach com IA leem seus números e os transformam em uma resposta clara: hoje avance ou recupere.", ru:"Оценка восстановления и ИИ-тренер читают ваши цифры и превращают их в чёткий ответ: сегодня ускоряться или восстанавливаться.", zh:"恢复评分与 AI 教练读取你的数据，给出明确答案：今天发力，还是恢复。", ar:"درجة التعافي ومدرّب الذكاء الاصطناعي يقرآن أرقامك ويحوّلانها إلى إجابة واضحة: اجتهد اليوم أم تعافَ." },
  "Accountability that sticks": { tr:"Kalıcı sorumluluk", de:"Verbindlichkeit, die bleibt", es:"Compromiso que perdura", fr:"Un engagement qui tient", it:"Motivazione che dura", ja:"続く責任感", ko:"오래가는 책임감", pt:"Compromisso que permanece", ru:"Ответственность, которая держится", zh:"持久的自律", ar:"التزام يدوم" },
  "Streaks, challenges and friends cheering you on keep you consistent long after motivation fades.": { tr:"Seriler, meydan okumalar ve seni destekleyen arkadaşlar, motivasyon bittikten çok sonra bile istikrarlı kalmanı sağlar.", de:"Serien, Challenges und Freunde, die dich anfeuern, halten dich beständig — lange nachdem die Motivation nachlässt.", es:"Las rachas, los retos y los amigos que te animan te mantienen constante mucho después de que baje la motivación.", fr:"Les séries, les défis et les amis qui vous encouragent vous gardent régulier bien après la baisse de motivation.", it:"Streak, sfide e amici che ti incoraggiano ti mantengono costante molto dopo che la motivazione cala.", ja:"連続記録、チャレンジ、応援してくれる友達が、モチベーションが下がった後もあなたを続けさせます。", ko:"연속 기록, 챌린지, 응원하는 친구들이 동기가 식은 뒤에도 꾸준함을 지켜 줍니다.", pt:"Sequências, desafios e amigos torcendo por você mantêm a constância muito depois de a motivação cair.", ru:"Серии, челленджи и поддержка друзей помогают держаться долго после того, как мотивация угасла.", zh:"连续打卡、挑战，以及为你加油的好友，让你在动力消退后依然坚持。", ar:"السلاسل والتحديات والأصدقاء الذين يشجّعونك تبقيك ملتزمًا بعد أن يخبو الحماس بوقت طويل." },
  "Notes / Spreadsheet": { tr:"Notlar / Tablo", de:"Notizen / Tabelle", es:"Notas / Hoja de cálculo", fr:"Notes / Tableur", it:"Note / Foglio di calcolo", ja:"メモ / 表計算", ko:"메모 / 스프레드시트", pt:"Notas / Planilha", ru:"Заметки / Таблица", zh:"笔记 / 表格", ar:"ملاحظات / جدول بيانات" },
  "Separate apps": { tr:"Ayrı uygulamalar", de:"Einzelne Apps", es:"Apps separadas", fr:"Apps séparées", it:"App separate", ja:"個別アプリ", ko:"개별 앱", pt:"Apps separados", ru:"Отдельные приложения", zh:"分散的应用", ar:"تطبيقات منفصلة" },
  "MyVitality": { tr:"MyVitality", de:"MyVitality", es:"MyVitality", fr:"MyVitality", it:"MyVitality", ja:"MyVitality", ko:"MyVitality", pt:"MyVitality", ru:"MyVitality", zh:"MyVitality", ar:"MyVitality" },
  "Automatic GPS workout tracking": { tr:"Otomatik GPS antrenman takibi", de:"Automatisches GPS-Workout-Tracking", es:"Registro automático de entrenos por GPS", fr:"Suivi GPS automatique des séances", it:"Tracciamento GPS automatico", ja:"GPSワークアウトの自動記録", ko:"자동 GPS 운동 추적", pt:"Registro automático de treinos por GPS", ru:"Автоматический GPS-трекинг тренировок", zh:"自动 GPS 训练记录", ar:"تتبّع تمارين GPS التلقائي" },
  "Recovery & HRV in context": { tr:"Bağlamıyla toparlanma ve HRV", de:"Erholung & HRV im Kontext", es:"Recuperación y HRV en contexto", fr:"Récupération & VFC en contexte", it:"Recupero e HRV nel contesto", ja:"文脈の中での回復とHRV", ko:"맥락 속 회복 & HRV", pt:"Recuperação e VFC em contexto", ru:"Восстановление и ВСР в контексте", zh:"结合情境的恢复与 HRV", ar:"التعافي وتقلب ضربات القلب ضمن السياق" },
  "Training, sleep & nutrition in one place": { tr:"Antrenman, uyku ve beslenme tek yerde", de:"Training, Schlaf & Ernährung an einem Ort", es:"Entreno, sueño y nutrición en un lugar", fr:"Entraînement, sommeil & nutrition au même endroit", it:"Allenamento, sonno e nutrizione in un posto", ja:"トレーニング・睡眠・栄養を一か所に", ko:"훈련·수면·영양을 한곳에", pt:"Treino, sono e nutrição em um só lugar", ru:"Тренировки, сон и питание в одном месте", zh:"训练、睡眠与营养集于一处", ar:"التمرين والنوم والتغذية في مكان واحد" },
  "AI coach grounded in your data": { tr:"Verilerine dayalı yapay zekâ koç", de:"KI-Coach auf Basis deiner Daten", es:"Coach con IA basado en tus datos", fr:"Coach IA fondé sur vos données", it:"Coach IA basato sui tuoi dati", ja:"あなたのデータに基づくAIコーチ", ko:"당신의 데이터 기반 AI 코치", pt:"Coach com IA baseado nos seus dados", ru:"ИИ-тренер на основе ваших данных", zh:"基于你数据的 AI 教练", ar:"مدرّب ذكاء اصطناعي مبني على بياناتك" },
  "Community & accountability": { tr:"Topluluk ve sorumluluk", de:"Community & Verbindlichkeit", es:"Comunidad y compromiso", fr:"Communauté & engagement", it:"Comunità e motivazione", ja:"コミュニティと責任感", ko:"커뮤니티 & 책임감", pt:"Comunidade e compromisso", ru:"Сообщество и ответственность", zh:"社区与自律", ar:"المجتمع والالتزام" },
  "Monthly cost": { tr:"Aylık ücret", de:"Monatliche Kosten", es:"Coste mensual", fr:"Coût mensuel", it:"Costo mensile", ja:"月額費用", ko:"월 비용", pt:"Custo mensal", ru:"Ежемесячная плата", zh:"每月费用", ar:"التكلفة الشهرية" },
  "Free, manual": { tr:"Ücretsiz, manuel", de:"Kostenlos, manuell", es:"Gratis, manual", fr:"Gratuit, manuel", it:"Gratis, manuale", ja:"無料・手動", ko:"무료, 수동", pt:"Grátis, manual", ru:"Бесплатно, вручную", zh:"免费，手动", ar:"مجاني، يدوي" },
  "Often $$$": { tr:"Genelde $$$", de:"Oft $$$", es:"A menudo $$$", fr:"Souvent $$$", it:"Spesso $$$", ja:"高額になりがち $$$", ko:"보통 $$$", pt:"Geralmente $$$", ru:"Часто $$$", zh:"通常 $$$", ar:"غالبًا $$$" },
  "Yes": { tr:"Evet", de:"Ja", es:"Sí", fr:"Oui", it:"Sì", ja:"あり", ko:"지원", pt:"Sim", ru:"Да", zh:"支持", ar:"نعم" },
  "Rarely": { tr:"Nadiren", de:"Selten", es:"Rara vez", fr:"Rarement", it:"Raramente", ja:"ほぼなし", ko:"드묾", pt:"Raramente", ru:"Редко", zh:"很少", ar:"نادرًا" },
  "Some": { tr:"Biraz", de:"Etwas", es:"Algo", fr:"Un peu", it:"In parte", ja:"一部のみ", ko:"일부", pt:"Algum", ru:"Отчасти", zh:"部分", ar:"بعضه" },
  "MyVitality is in active development. Want to help shape it? Join the beta →": {
    tr:"MyVitality aktif geliştirme aşamasında. Şekillenmesine yardım etmek ister misin? <a href='mailto:egemizrak@icloud.com?subject=MyVitality%20beta'>Beta'ya katıl →</a>",
    de:"MyVitality befindet sich in aktiver Entwicklung. Willst du mitgestalten? <a href='mailto:egemizrak@icloud.com?subject=MyVitality%20beta'>Zur Beta →</a>",
    es:"MyVitality está en desarrollo activo. ¿Quieres ayudar a moldearla? <a href='mailto:egemizrak@icloud.com?subject=MyVitality%20beta'>Únete a la beta →</a>",
    fr:"MyVitality est en développement actif. Envie de contribuer ? <a href='mailto:egemizrak@icloud.com?subject=MyVitality%20beta'>Rejoindre la bêta →</a>",
    it:"MyVitality è in sviluppo attivo. Vuoi contribuire a plasmarla? <a href='mailto:egemizrak@icloud.com?subject=MyVitality%20beta'>Unisciti alla beta →</a>",
    ja:"MyVitalityは活発に開発中です。形づくりを手伝いませんか？ <a href='mailto:egemizrak@icloud.com?subject=MyVitality%20beta'>ベータに参加 →</a>",
    ko:"MyVitality는 활발히 개발 중입니다. 함께 만들어 보실래요? <a href='mailto:egemizrak@icloud.com?subject=MyVitality%20beta'>베타 참여 →</a>",
    pt:"O MyVitality está em desenvolvimento ativo. Quer ajudar a moldá-lo? <a href='mailto:egemizrak@icloud.com?subject=MyVitality%20beta'>Entrar na beta →</a>",
    ru:"MyVitality в активной разработке. Хотите повлиять на него? <a href='mailto:egemizrak@icloud.com?subject=MyVitality%20beta'>Вступить в бету →</a>",
    zh:"MyVitality 正在积极开发中。想帮忙塑造它吗？<a href='mailto:egemizrak@icloud.com?subject=MyVitality%20beta'>加入测试 →</a>",
    ar:"MyVitality قيد التطوير النشط. هل تريد المساهمة في تشكيله؟ <a href='mailto:egemizrak@icloud.com?subject=MyVitality%20beta'>انضمّ إلى النسخة التجريبية →</a>"
  },

  // ── FAQ ──
  "FAQ": { tr:"SSS", de:"FAQ", es:"Preguntas frecuentes", fr:"FAQ", it:"FAQ", ja:"よくある質問", ko:"자주 묻는 질문", pt:"Perguntas frequentes", ru:"Вопросы и ответы", zh:"常见问题", ar:"الأسئلة الشائعة" },
  "Frequently asked questions": { tr:"Sıkça sorulan sorular", de:"Häufige Fragen", es:"Preguntas frecuentes", fr:"Questions fréquentes", it:"Domande frequenti", ja:"よくある質問", ko:"자주 묻는 질문", pt:"Perguntas frequentes", ru:"Часто задаваемые вопросы", zh:"常见问题", ar:"الأسئلة المتكرّرة" },
  "How much does MyVitality cost?": { tr:"MyVitality ne kadar?", de:"Was kostet MyVitality?", es:"¿Cuánto cuesta MyVitality?", fr:"Combien coûte MyVitality ?", it:"Quanto costa MyVitality?", ja:"MyVitalityの料金は？", ko:"MyVitality 요금은 얼마인가요?", pt:"Quanto custa o MyVitality?", ru:"Сколько стоит MyVitality?", zh:"MyVitality 多少钱？", ar:"كم تبلغ تكلفة MyVitality؟" },
  "MyVitality starts with a free trial, then $6.99/month — shown in your local currency (£6.99 in the UK, €6.99 in Europe, ₺300 in Turkey). One subscription covers everything, with no ads. See the pricing page for details.": {
    tr:"MyVitality ücretsiz denemeyle başlar, sonra ayda $6.99 — yerel para biriminle gösterilir (İngiltere'de £6.99, Avrupa'da €6.99, Türkiye'de ₺300). Tek abonelik her şeyi kapsar, reklam yok. Ayrıntılar için <a href='/pricing/'>fiyatlandırma sayfasına</a> bak.",
    de:"MyVitality startet mit einer kostenlosen Testphase, danach 6,99 $/Monat — in deiner lokalen Währung (£6.99 in UK, €6.99 in Europa, ₺300 in der Türkei). Ein Abo deckt alles ab, ohne Werbung. Details auf der <a href='/pricing/'>Preisseite</a>.",
    es:"MyVitality empieza con una prueba gratuita y luego $6.99/mes — en tu moneda local (£6.99 en el Reino Unido, €6.99 en Europa, ₺300 en Turquía). Una suscripción cubre todo, sin anuncios. Mira la <a href='/pricing/'>página de precios</a> para más detalles.",
    fr:"MyVitality commence par un essai gratuit, puis 6,99 $/mois — dans votre devise locale (£6.99 au Royaume-Uni, €6.99 en Europe, ₺300 en Turquie). Un seul abonnement couvre tout, sans publicité. Voir la <a href='/pricing/'>page des tarifs</a>.",
    it:"MyVitality inizia con una prova gratuita, poi $6.99/mese — nella tua valuta locale (£6.99 nel Regno Unito, €6.99 in Europa, ₺300 in Turchia). Un solo abbonamento copre tutto, senza pubblicità. Vedi la <a href='/pricing/'>pagina dei prezzi</a>.",
    ja:"MyVitalityは無料トライアルから始まり、その後は月額$6.99 — 現地通貨で表示されます（英国£6.99、欧州€6.99、トルコ₺300）。1つのサブスクですべて利用でき、広告はありません。詳しくは<a href='/pricing/'>料金ページ</a>へ。",
    ko:"MyVitality는 무료 체험으로 시작하고 이후 월 $6.99입니다 — 현지 통화로 표시됩니다(영국 £6.99, 유럽 €6.99, 튀르키예 ₺300). 하나의 구독으로 모든 기능을 광고 없이 이용합니다. 자세한 내용은 <a href='/pricing/'>요금 페이지</a>를 확인하세요.",
    pt:"O MyVitality começa com um teste grátis e depois $6.99/mês — na sua moeda local (£6.99 no Reino Unido, €6.99 na Europa, ₺300 na Turquia). Uma assinatura cobre tudo, sem anúncios. Veja a <a href='/pricing/'>página de preços</a>.",
    ru:"MyVitality начинается с бесплатного периода, затем $6.99/месяц — в вашей валюте (£6.99 в Великобритании, €6.99 в Европе, ₺300 в Турции). Одна подписка покрывает всё, без рекламы. Подробнее на <a href='/pricing/'>странице цен</a>.",
    zh:"MyVitality 以免费试用开始，之后每月 $6.99 — 以你的本地货币显示（英国 £6.99，欧洲 €6.99，土耳其 ₺300）。一个订阅涵盖全部功能，且无广告。详见<a href='/pricing/'>价格页面</a>。",
    ar:"يبدأ MyVitality بتجربة مجانية، ثم 6.99$ شهريًا — معروضًا بعملتك المحلية (£6.99 في المملكة المتحدة، €6.99 في أوروبا، ₺300 في تركيا). اشتراك واحد يشمل كل شيء، بلا إعلانات. اطّلع على <a href='/pricing/'>صفحة الأسعار</a> للتفاصيل."
  },
  "Does it work on iPhone and Android?": { tr:"iPhone ve Android'de çalışır mı?", de:"Funktioniert es auf iPhone und Android?", es:"¿Funciona en iPhone y Android?", fr:"Fonctionne-t-il sur iPhone et Android ?", it:"Funziona su iPhone e Android?", ja:"iPhoneとAndroidで使えますか？", ko:"아이폰과 안드로이드에서 작동하나요?", pt:"Funciona no iPhone e Android?", ru:"Работает ли на iPhone и Android?", zh:"支持 iPhone 和安卓吗？", ar:"هل يعمل على iPhone وAndroid؟" },
  "MyVitality launches first on iPhone and Apple Watch. An Android version is on the roadmap — let us know if you'd like to be notified.": {
    tr:"MyVitality önce iPhone ve Apple Watch'ta çıkıyor. Android sürümü yol haritasında — haberdar olmak istersen <a href='mailto:egemizrak@icloud.com?subject=MyVitality%20Android'>bize bildir</a>.",
    de:"MyVitality startet zuerst auf iPhone und Apple Watch. Eine Android-Version ist geplant — <a href='mailto:egemizrak@icloud.com?subject=MyVitality%20Android'>sag uns Bescheid</a>, wenn du benachrichtigt werden möchtest.",
    es:"MyVitality se lanza primero en iPhone y Apple Watch. Una versión Android está en la hoja de ruta — <a href='mailto:egemizrak@icloud.com?subject=MyVitality%20Android'>avísanos</a> si quieres que te notifiquemos.",
    fr:"MyVitality sort d'abord sur iPhone et Apple Watch. Une version Android est prévue — <a href='mailto:egemizrak@icloud.com?subject=MyVitality%20Android'>dites-nous</a> si vous souhaitez être prévenu.",
    it:"MyVitality debutta prima su iPhone e Apple Watch. Una versione Android è in programma — <a href='mailto:egemizrak@icloud.com?subject=MyVitality%20Android'>facci sapere</a> se vuoi essere avvisato.",
    ja:"MyVitalityはまずiPhoneとApple Watchで提供されます。Android版も予定中 — 通知をご希望なら<a href='mailto:egemizrak@icloud.com?subject=MyVitality%20Android'>お知らせください</a>。",
    ko:"MyVitality는 먼저 아이폰과 Apple Watch에 출시됩니다. 안드로이드 버전도 로드맵에 있습니다 — 알림을 원하시면 <a href='mailto:egemizrak@icloud.com?subject=MyVitality%20Android'>알려 주세요</a>.",
    pt:"O MyVitality chega primeiro ao iPhone e Apple Watch. Uma versão Android está no roadmap — <a href='mailto:egemizrak@icloud.com?subject=MyVitality%20Android'>avise-nos</a> se quiser ser notificado.",
    ru:"MyVitality сначала выходит на iPhone и Apple Watch. Версия для Android в планах — <a href='mailto:egemizrak@icloud.com?subject=MyVitality%20Android'>сообщите нам</a>, если хотите получить уведомление.",
    zh:"MyVitality 先在 iPhone 和 Apple Watch 上线。安卓版已在规划中 — 如需通知，请<a href='mailto:egemizrak@icloud.com?subject=MyVitality%20Android'>告诉我们</a>。",
    ar:"يُطلق MyVitality أولًا على iPhone وApple Watch. ونسخة Android ضمن خططنا — <a href='mailto:egemizrak@icloud.com?subject=MyVitality%20Android'>أخبرنا</a> إن أردت أن نُعلِمك."
  },
  "Can I track workouts manually?": { tr:"Antrenmanları elle ekleyebilir miyim?", de:"Kann ich Workouts manuell erfassen?", es:"¿Puedo registrar entrenos manualmente?", fr:"Puis-je enregistrer des séances manuellement ?", it:"Posso registrare gli allenamenti manualmente?", ja:"ワークアウトを手動で記録できますか？", ko:"운동을 수동으로 기록할 수 있나요?", pt:"Posso registrar treinos manualmente?", ru:"Можно ли добавлять тренировки вручную?", zh:"我可以手动记录训练吗？", ar:"هل يمكنني تسجيل التمارين يدويًا؟" },
  "Yes. You can record a GPS workout in real time or add one manually with distance, duration and activity type. Learn more on the workout tracker page.": {
    tr:"Evet. GPS antrenmanını gerçek zamanlı kaydedebilir ya da mesafe, süre ve aktivite türüyle elle ekleyebilirsin. Daha fazlası için <a href='/workout-tracker/'>antrenman takibi sayfasına</a> bak.",
    de:"Ja. Du kannst ein GPS-Workout in Echtzeit aufzeichnen oder manuell mit Distanz, Dauer und Aktivitätstyp hinzufügen. Mehr auf der <a href='/workout-tracker/'>Workout-Tracker-Seite</a>.",
    es:"Sí. Puedes grabar un entreno con GPS en tiempo real o añadirlo manualmente con distancia, duración y tipo de actividad. Más info en la <a href='/workout-tracker/'>página del registro de entrenos</a>.",
    fr:"Oui. Vous pouvez enregistrer une séance GPS en temps réel ou l'ajouter manuellement avec distance, durée et type d'activité. Plus d'infos sur la <a href='/workout-tracker/'>page de suivi des séances</a>.",
    it:"Sì. Puoi registrare un allenamento GPS in tempo reale o aggiungerlo manualmente con distanza, durata e tipo di attività. Scopri di più nella <a href='/workout-tracker/'>pagina del tracker allenamenti</a>.",
    ja:"はい。GPSワークアウトをリアルタイムで記録するか、距離・時間・種目を入力して手動で追加できます。詳しくは<a href='/workout-tracker/'>ワークアウト記録ページ</a>へ。",
    ko:"네. GPS 운동을 실시간으로 기록하거나 거리·시간·활동 종류로 수동 추가할 수 있습니다. 자세한 내용은 <a href='/workout-tracker/'>운동 추적 페이지</a>를 확인하세요.",
    pt:"Sim. Você pode gravar um treino com GPS em tempo real ou adicioná-lo manualmente com distância, duração e tipo de atividade. Saiba mais na <a href='/workout-tracker/'>página de registro de treinos</a>.",
    ru:"Да. Можно записать GPS-тренировку в реальном времени или добавить вручную с дистанцией, длительностью и типом активности. Подробнее на <a href='/workout-tracker/'>странице трекера тренировок</a>.",
    zh:"可以。你可以实时记录 GPS 训练，也可以手动添加距离、时长和运动类型。详见<a href='/workout-tracker/'>训练记录页面</a>。",
    ar:"نعم. يمكنك تسجيل تمرين GPS فوريًا أو إضافته يدويًا مع المسافة والمدة ونوع النشاط. اعرف المزيد في <a href='/workout-tracker/'>صفحة متتبّع التمارين</a>."
  },
  "Does it connect to Apple Health?": { tr:"Apple Health'e bağlanır mı?", de:"Verbindet es sich mit Apple Health?", es:"¿Se conecta con Apple Health?", fr:"Se connecte-t-il à Apple Health ?", it:"Si collega ad Apple Health?", ja:"Apple Healthと連携しますか？", ko:"Apple Health와 연동되나요?", pt:"Conecta com o Apple Health?", ru:"Подключается ли к Apple Health?", zh:"能连接 Apple Health 吗？", ar:"هل يتصل بـ Apple Health؟" },
  "Yes. MyVitality reads heart rate, HRV, sleep, steps and more from Apple Health, so any device that syncs to Apple Health works automatically.": { tr:"Evet. MyVitality; nabız, HRV, uyku, adım ve daha fazlasını Apple Health'ten okur, böylece Apple Health ile senkronize olan her cihaz otomatik çalışır.", de:"Ja. MyVitality liest Herzfrequenz, HRV, Schlaf, Schritte und mehr aus Apple Health — jedes Gerät, das mit Apple Health synchronisiert, funktioniert automatisch.", es:"Sí. MyVitality lee frecuencia cardiaca, HRV, sueño, pasos y más desde Apple Health, así que cualquier dispositivo que sincronice con Apple Health funciona automáticamente.", fr:"Oui. MyVitality lit fréquence cardiaque, VFC, sommeil, pas et plus depuis Apple Health, donc tout appareil synchronisé à Apple Health fonctionne automatiquement.", it:"Sì. MyVitality legge frequenza cardiaca, HRV, sonno, passi e altro da Apple Health, quindi qualsiasi dispositivo sincronizzato con Apple Health funziona automaticamente.", ja:"はい。MyVitalityは心拍・HRV・睡眠・歩数などをApple Healthから読み取るため、Apple Healthと同期するデバイスは自動で機能します。", ko:"네. MyVitality는 심박수, HRV, 수면, 걸음 수 등을 Apple Health에서 읽어오므로 Apple Health와 동기화되는 모든 기기가 자동으로 작동합니다.", pt:"Sim. O MyVitality lê frequência cardíaca, VFC, sono, passos e mais do Apple Health, então qualquer dispositivo que sincroniza com o Apple Health funciona automaticamente.", ru:"Да. MyVitality читает пульс, ВСР, сон, шаги и другое из Apple Health, поэтому любое синхронизирующееся устройство работает автоматически.", zh:"可以。MyVitality 从 Apple Health 读取心率、HRV、睡眠、步数等，因此任何同步到 Apple Health 的设备都能自动工作。", ar:"نعم. يقرأ MyVitality نبض القلب وتقلبه والنوم والخطوات والمزيد من Apple Health، لذا يعمل أي جهاز يتزامن مع Apple Health تلقائيًا." },
  "Can I use it without a wearable?": { tr:"Giyilebilir cihaz olmadan kullanabilir miyim?", de:"Kann ich es ohne Wearable nutzen?", es:"¿Puedo usarla sin un wearable?", fr:"Puis-je l'utiliser sans objet connecté ?", it:"Posso usarla senza un indossabile?", ja:"ウェアラブルなしで使えますか？", ko:"웨어러블 없이 사용할 수 있나요?", pt:"Posso usar sem um wearable?", ru:"Можно ли пользоваться без носимого устройства?", zh:"没有可穿戴设备也能用吗？", ar:"هل يمكنني استخدامه بدون جهاز يُرتدى؟" },
  "Yes. You can track GPS workouts with just your iPhone and log nutrition and weight manually. A smartwatch adds recovery, HRV and sleep data.": {
    tr:"Evet. Sadece iPhone'unla GPS antrenmanlarını takip edebilir, beslenme ve kiloyu elle kaydedebilirsin. Akıllı saat, toparlanma, HRV ve <a href='/sleep-tracker/'>uyku</a> verisi ekler.",
    de:"Ja. Du kannst GPS-Workouts nur mit dem iPhone verfolgen und Ernährung und Gewicht manuell loggen. Eine Smartwatch ergänzt Erholung, HRV und <a href='/sleep-tracker/'>Schlaf</a>-Daten.",
    es:"Sí. Puedes registrar entrenos con GPS solo con tu iPhone y anotar nutrición y peso manualmente. Un smartwatch añade datos de recuperación, HRV y <a href='/sleep-tracker/'>sueño</a>.",
    fr:"Oui. Vous pouvez suivre des séances GPS avec votre seul iPhone et noter nutrition et poids manuellement. Une montre connectée ajoute récupération, VFC et données de <a href='/sleep-tracker/'>sommeil</a>.",
    it:"Sì. Puoi tracciare allenamenti GPS solo con l'iPhone e annotare nutrizione e peso manualmente. Uno smartwatch aggiunge dati di recupero, HRV e <a href='/sleep-tracker/'>sonno</a>.",
    ja:"はい。iPhoneだけでGPSワークアウトを記録し、栄養と体重を手動で入力できます。スマートウォッチがあれば回復・HRV・<a href='/sleep-tracker/'>睡眠</a>データが加わります。",
    ko:"네. 아이폰만으로 GPS 운동을 추적하고 영양과 체중을 수동으로 기록할 수 있습니다. 스마트워치가 있으면 회복, HRV, <a href='/sleep-tracker/'>수면</a> 데이터가 추가됩니다.",
    pt:"Sim. Você pode registrar treinos com GPS só com o iPhone e anotar nutrição e peso manualmente. Um smartwatch adiciona dados de recuperação, VFC e <a href='/sleep-tracker/'>sono</a>.",
    ru:"Да. Можно отслеживать GPS-тренировки только с iPhone и вручную записывать питание и вес. Часы добавляют данные о восстановлении, ВСР и <a href='/sleep-tracker/'>сне</a>.",
    zh:"可以。仅用 iPhone 即可记录 GPS 训练，并手动记录营养和体重。智能手表会增加恢复、HRV 和<a href='/sleep-tracker/'>睡眠</a>数据。",
    ar:"نعم. يمكنك تتبّع تمارين GPS بهاتفك فقط وتسجيل التغذية والوزن يدويًا. أما الساعة الذكية فتضيف بيانات التعافي وتقلب ضربات القلب و<a href='/sleep-tracker/'>النوم</a>."
  },
  "What fitness metrics should I track?": { tr:"Hangi fitness metriklerini takip etmeliyim?", de:"Welche Fitness-Werte sollte ich verfolgen?", es:"¿Qué métricas de fitness debería seguir?", fr:"Quels indicateurs de forme suivre ?", it:"Quali parametri di fitness dovrei monitorare?", ja:"どのフィットネス指標を記録すべき？", ko:"어떤 피트니스 지표를 추적해야 하나요?", pt:"Quais métricas de fitness devo acompanhar?", ru:"Какие фитнес-показатели отслеживать?", zh:"我该追踪哪些健身指标？", ar:"ما مؤشرات اللياقة التي ينبغي تتبّعها؟" },
  "Start simple: workouts, sleep and a weekly check on recovery. Our blog covers the best fitness metrics to track every week.": {
    tr:"Basit başla: antrenmanlar, uyku ve haftalık bir <a href='/recovery-tracker/'>toparlanma</a> kontrolü. Blogumuz <a href='/blog/best-fitness-metrics-to-track/'>her hafta takip edilecek en iyi fitness metriklerini</a> anlatıyor.",
    de:"Fang einfach an: Workouts, Schlaf und ein wöchentlicher Blick auf die <a href='/recovery-tracker/'>Erholung</a>. Unser Blog zeigt <a href='/blog/best-fitness-metrics-to-track/'>die besten Fitness-Werte für jede Woche</a>.",
    es:"Empieza simple: entrenos, sueño y un repaso semanal de la <a href='/recovery-tracker/'>recuperación</a>. Nuestro blog cubre <a href='/blog/best-fitness-metrics-to-track/'>las mejores métricas de fitness para seguir cada semana</a>.",
    fr:"Commencez simple : séances, sommeil et un point hebdomadaire sur la <a href='/recovery-tracker/'>récupération</a>. Notre blog présente <a href='/blog/best-fitness-metrics-to-track/'>les meilleurs indicateurs de forme à suivre chaque semaine</a>.",
    it:"Inizia semplice: allenamenti, sonno e un controllo settimanale del <a href='/recovery-tracker/'>recupero</a>. Il nostro blog spiega <a href='/blog/best-fitness-metrics-to-track/'>i migliori parametri di fitness da seguire ogni settimana</a>.",
    ja:"シンプルに始めましょう。ワークアウト、睡眠、そして週1回の<a href='/recovery-tracker/'>回復</a>チェック。ブログでは<a href='/blog/best-fitness-metrics-to-track/'>毎週追うべき最適なフィットネス指標</a>を紹介しています。",
    ko:"간단하게 시작하세요: 운동, 수면, 그리고 주 1회 <a href='/recovery-tracker/'>회복</a> 점검. 블로그에서 <a href='/blog/best-fitness-metrics-to-track/'>매주 추적하기 좋은 피트니스 지표</a>를 다룹니다.",
    pt:"Comece simples: treinos, sono e uma checagem semanal da <a href='/recovery-tracker/'>recuperação</a>. Nosso blog cobre <a href='/blog/best-fitness-metrics-to-track/'>as melhores métricas de fitness para acompanhar toda semana</a>.",
    ru:"Начните с простого: тренировки, сон и еженедельная проверка <a href='/recovery-tracker/'>восстановления</a>. В нашем блоге — <a href='/blog/best-fitness-metrics-to-track/'>лучшие фитнес-показатели для еженедельного контроля</a>.",
    zh:"从简单开始：训练、睡眠，以及每周一次的<a href='/recovery-tracker/'>恢复</a>检查。我们的博客介绍了<a href='/blog/best-fitness-metrics-to-track/'>每周值得追踪的最佳健身指标</a>。",
    ar:"ابدأ ببساطة: التمارين والنوم وفحص أسبوعي لـ<a href='/recovery-tracker/'>التعافي</a>. تتناول مدونتنا <a href='/blog/best-fitness-metrics-to-track/'>أفضل مؤشرات اللياقة لمتابعتها كل أسبوع</a>."
  },
  "Is my health data private?": { tr:"Sağlık verilerim gizli mi?", de:"Sind meine Gesundheitsdaten privat?", es:"¿Mis datos de salud son privados?", fr:"Mes données de santé sont-elles privées ?", it:"I miei dati sulla salute sono privati?", ja:"健康データは非公開ですか？", ko:"내 건강 데이터는 비공개인가요?", pt:"Meus dados de saúde são privados?", ru:"Мои данные о здоровье конфиденциальны?", zh:"我的健康数据是私密的吗？", ar:"هل بياناتي الصحية خاصة؟" },
  "Yes. Your health data is never sold, never shared with advertisers and never used for marketing. Read the full privacy policy.": {
    tr:"Evet. Sağlık verilerin asla satılmaz, reklamcılarla paylaşılmaz ve pazarlama için kullanılmaz. Tüm <a href='/privacy-policy/'>gizlilik politikasını</a> oku.",
    de:"Ja. Deine Gesundheitsdaten werden nie verkauft, nie an Werbetreibende weitergegeben und nie für Marketing genutzt. Lies die vollständige <a href='/privacy-policy/'>Datenschutzerklärung</a>.",
    es:"Sí. Tus datos de salud nunca se venden, ni se comparten con anunciantes, ni se usan para marketing. Lee la <a href='/privacy-policy/'>política de privacidad</a> completa.",
    fr:"Oui. Vos données de santé ne sont jamais vendues, ni partagées avec des annonceurs, ni utilisées à des fins marketing. Lisez la <a href='/privacy-policy/'>politique de confidentialité</a> complète.",
    it:"Sì. I tuoi dati sulla salute non vengono mai venduti, condivisi con inserzionisti o usati per marketing. Leggi l'intera <a href='/privacy-policy/'>informativa sulla privacy</a>.",
    ja:"はい。あなたの健康データが販売・広告主への共有・マーケティング利用されることは一切ありません。詳しくは<a href='/privacy-policy/'>プライバシーポリシー</a>をご覧ください。",
    ko:"네. 당신의 건강 데이터는 절대 판매되거나, 광고주와 공유되거나, 마케팅에 사용되지 않습니다. 전체 <a href='/privacy-policy/'>개인정보 처리방침</a>을 읽어보세요.",
    pt:"Sim. Seus dados de saúde nunca são vendidos, compartilhados com anunciantes ou usados para marketing. Leia a <a href='/privacy-policy/'>política de privacidade</a> completa.",
    ru:"Да. Ваши данные о здоровье никогда не продаются, не передаются рекламодателям и не используются для маркетинга. Читайте полную <a href='/privacy-policy/'>политику конфиденциальности</a>.",
    zh:"是的。你的健康数据绝不出售、绝不分享给广告商、绝不用于营销。请阅读完整的<a href='/privacy-policy/'>隐私政策</a>。",
    ar:"نعم. لا تُباع بياناتك الصحية أبدًا، ولا تُشارك مع المعلنين، ولا تُستخدم للتسويق. اقرأ <a href='/privacy-policy/'>سياسة الخصوصية</a> كاملة."
  },
  "How is this different from Strava or Whoop?": { tr:"Bunun Strava veya Whoop'tan farkı ne?", de:"Worin unterscheidet es sich von Strava oder Whoop?", es:"¿En qué se diferencia de Strava o Whoop?", fr:"En quoi est-ce différent de Strava ou Whoop ?", it:"In cosa è diverso da Strava o Whoop?", ja:"StravaやWhoopと何が違いますか？", ko:"Strava나 Whoop와 무엇이 다른가요?", pt:"Como isso difere do Strava ou Whoop?", ru:"Чем это отличается от Strava или Whoop?", zh:"它和 Strava 或 Whoop 有何不同？", ar:"بماذا يختلف عن Strava أو Whoop؟" },
  "MyVitality combines GPS workout tracking, recovery and HRV, sleep, nutrition, an AI coach and community in one app — instead of paying for several separate subscriptions.": { tr:"MyVitality; GPS antrenman takibi, toparlanma ve HRV, uyku, beslenme, yapay zekâ koç ve topluluğu tek uygulamada birleştirir — birkaç ayrı aboneliğe ödeme yapmak yerine.", de:"MyVitality vereint GPS-Workout-Tracking, Erholung & HRV, Schlaf, Ernährung, einen KI-Coach und Community in einer App — statt mehrere separate Abos zu zahlen.", es:"MyVitality combina registro de entrenos por GPS, recuperación y HRV, sueño, nutrición, un coach con IA y comunidad en una sola app — en lugar de pagar varias suscripciones separadas.", fr:"MyVitality réunit suivi GPS des séances, récupération et VFC, sommeil, nutrition, un coach IA et la communauté dans une seule app — au lieu de payer plusieurs abonnements séparés.", it:"MyVitality unisce tracciamento GPS, recupero e HRV, sonno, nutrizione, un coach IA e la comunità in un'unica app — invece di pagare più abbonamenti separati.", ja:"MyVitalityはGPSワークアウト記録、回復とHRV、睡眠、栄養、AIコーチ、コミュニティを1つのアプリに統合 — 複数の別々のサブスクに払う必要はありません。", ko:"MyVitality는 GPS 운동 추적, 회복과 HRV, 수면, 영양, AI 코치, 커뮤니티를 하나의 앱에 결합합니다 — 여러 개의 개별 구독에 돈을 쓰는 대신에요.", pt:"O MyVitality combina registro de treinos por GPS, recuperação e VFC, sono, nutrição, um coach com IA e comunidade em um só app — em vez de pagar várias assinaturas separadas.", ru:"MyVitality объединяет GPS-трекинг тренировок, восстановление и ВСР, сон, питание, ИИ-тренера и сообщество в одном приложении — вместо нескольких отдельных подписок.", zh:"MyVitality 将 GPS 训练记录、恢复与 HRV、睡眠、营养、AI 教练和社区整合在一个应用中 — 无需为多个独立订阅付费。", ar:"يجمع MyVitality تتبّع تمارين GPS والتعافي وتقلب ضربات القلب والنوم والتغذية ومدرّب ذكاء اصطناعي والمجتمع في تطبيق واحد — بدلًا من دفع عدة اشتراكات منفصلة." },

  // ── CTA ──
  "Ready to train smarter?": { tr:"Daha akıllı antrenmana <span class='grad'>hazır mısın?</span>", de:"Bereit, <span class='grad'>klüger zu trainieren?</span>", es:"¿Listo para entrenar <span class='grad'>más inteligente?</span>", fr:"Prêt à <span class='grad'>mieux vous entraîner ?</span>", it:"Pronto ad allenarti <span class='grad'>in modo più intelligente?</span>", ja:"もっと賢く<span class='grad'>トレーニングしませんか？</span>", ko:"더 똑똑하게 <span class='grad'>훈련할 준비됐나요?</span>", pt:"Pronto para treinar <span class='grad'>com mais inteligência?</span>", ru:"Готовы тренироваться <span class='grad'>умнее?</span>", zh:"准备好更聪明地<span class='grad'>训练了吗？</span>", ar:"مستعدّ للتدرّب <span class='grad'>بذكاء أكبر؟</span>" },
  "Free trial, then $6.99/month in your local currency — launching on iOS soon. Join the early-access list and we'll email you the moment it's live.": { tr:"Ücretsiz deneme, sonra yerel para biriminle ayda $6.99 — yakında iOS'ta. Erken erişim listesine katıl, yayına girer girmez sana e-posta atalım.", de:"Kostenlose Testphase, danach 6,99 $/Monat in deiner lokalen Währung — bald auf iOS. Trag dich in die Early-Access-Liste ein, wir mailen dir, sobald es live ist.", es:"Prueba gratuita y luego $6.99/mes en tu moneda local — pronto en iOS. Únete a la lista de acceso anticipado y te avisamos por correo en cuanto esté disponible.", fr:"Essai gratuit, puis 6,99 $/mois dans votre devise locale — bientôt sur iOS. Inscrivez-vous à l'accès anticipé et nous vous écrirons dès le lancement.", it:"Prova gratuita, poi $6.99/mese nella tua valuta locale — presto su iOS. Iscriviti all'accesso anticipato e ti scriviamo appena è disponibile.", ja:"無料トライアル、その後は現地通貨で月額$6.99 — まもなくiOSに登場。先行アクセスリストに参加すれば、公開と同時にメールでお知らせします。", ko:"무료 체험 후 현지 통화로 월 $6.99 — 곧 iOS 출시. 얼리 액세스 목록에 등록하면 출시되는 순간 이메일로 알려드립니다.", pt:"Teste grátis e depois $6.99/mês na sua moeda local — em breve no iOS. Entre na lista de acesso antecipado e avisaremos por e-mail assim que estiver no ar.", ru:"Бесплатный период, затем $6.99/месяц в вашей валюте — скоро в iOS. Запишитесь в список раннего доступа, и мы напишем, как только всё заработает.", zh:"免费试用，之后每月 $6.99（以本地货币计）— 即将登陆 iOS。加入抢先体验名单，上线后我们会第一时间发邮件通知你。", ar:"تجربة مجانية، ثم 6.99$ شهريًا بعملتك المحلية — قريبًا على iOS. انضمّ إلى قائمة الوصول المبكر وسنراسلك فور الإطلاق." },
  "No spam. One email at launch. Unsubscribe anytime.": { tr:"Spam yok. Lansmanda tek e-posta. İstediğin zaman çık.", de:"Kein Spam. Eine E-Mail zum Start. Jederzeit abbestellbar.", es:"Sin spam. Un correo en el lanzamiento. Cancela cuando quieras.", fr:"Pas de spam. Un e-mail au lancement. Désabonnement à tout moment.", it:"Niente spam. Una mail al lancio. Disiscriviti quando vuoi.", ja:"スパムなし。公開時に1通のみ。いつでも解除できます。", ko:"스팸 없음. 출시 때 한 통만. 언제든 구독 해지 가능.", pt:"Sem spam. Um e-mail no lançamento. Cancele quando quiser.", ru:"Без спама. Одно письмо на старте. Отписка в любой момент.", zh:"无垃圾邮件。上线时仅发一封。可随时退订。", ar:"بلا رسائل مزعجة. بريد واحد عند الإطلاق. يمكنك إلغاء الاشتراك في أي وقت." }
};

const out = {};
LANGS.forEach(function (l) { out[l] = {}; });
Object.keys(T).forEach(function (en) {
  LANGS.forEach(function (l) { if (T[en][l] != null) out[l][en] = T[en][l]; });
});
const dir = path.join(__dirname, 'i18n');
fs.mkdirSync(dir, { recursive: true });
LANGS.forEach(function (l) {
  fs.writeFileSync(path.join(dir, l + '.json'), JSON.stringify(out[l]));
});
console.log('i18n: wrote ' + LANGS.length + ' files, ' + Object.keys(T).length + ' keys each (max).');
